# -*- coding: utf-8 -*-
# v2
"""Conteúdo dos guias de TEXTO (PT/ES/EN) — BFWC 2026.

Passos: h = título, b = corpo (markup <b>), table = tabela de campos (opcional).
"""

TXT = {
# ══════════════════════════════ PT ══════════════════════════════
'pt': {
  'filename': 'Guia-de-Inscricao-dos-Times-BFWC2026-PT.pdf',
  'title': 'Guia de Inscrição dos Times',
  'subtitle': 'Brasil Flag World Championship 2026 · Passo a passo completo, da criação da conta ao envio da escalação',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'PRAZOS DE INSCRIÇÃO',
  'deadlines_body': 'De <b>07/07 a 12/07</b>, a inscrição é exclusiva para times <b>já pré-inscritos</b> — use o <b>mesmo e-mail</b> informado na pré-inscrição. A partir de <b>13/07</b>, o cadastro fica aberto para qualquer time. <b>Vagas limitadas:</b> as vagas por categoria são preenchidas por ordem de inscrição e reserva — garante a vaga quem paga a 1ª parcela primeiro. Quando a categoria lota, as inscrições encerram.',
  'contact': 'Dúvidas? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'RESUMO — LINHA DO TEMPO DA INSCRIÇÃO',
  'timeline': [
    ('1', 'Cadastro do clube', '07/07 a 12/07 — pré-inscritos · a partir de 13/07 — aberto a todos'),
    ('2', 'Escolha das categorias', 'Na criação da conta (Etapa 2 do cadastro)'),
    ('3', 'Pagamento da 1ª parcela — <b>garante a vaga</b>', 'Até <b>20/07</b> · vagas preenchidas pelos pagamentos efetuados primeiro'),
    ('4', 'Pagamento das parcelas restantes', '2ª até 20/08 · 3ª até 20/09'),
    ('5', 'Inscrição dos atletas', 'Até 30/09'),
    ('6', 'Envio da escalação', 'Até 30/09'),
    ('✓', '<b>Inscrição finalizada!</b>', 'Nos vemos em Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Criar a conta do clube', 'steps': [
      {'h': 'Acesse a página de cadastro',
       'b': 'Entre em <b>www.brasilflagworldchampionship.com</b>, vá em <b>Portal</b> e escolha <b>Cadastro de Clube</b> (ou acesse direto <b>/portal/times/cadastro</b>). Funciona no celular e no computador.'},
      {'h': 'Escolha o idioma',
       'b': 'Na primeira tela, selecione <b>Português</b>, <b>English</b> ou <b>Español</b>. Todo o portal seguirá o idioma escolhido.'},
      {'h': 'Etapa 1 · Preencha os dados do clube',
       'b': '<b>Esse cadastro será utilizado durante todo o campeonato.</b> Campos marcados com * são obrigatórios:',
       'table': [
         ('Nome do clube *', 'Nome oficial do clube/organização'),
         ('País * e Cidade', 'Selecione o país na lista; cidade é opcional'),
         ('Nome do responsável *', 'Pessoa de contato do clube'),
         ('Cargo / Função', 'Ex.: presidente, técnico (opcional)'),
         ('E-mail *', 'Será usado no login e nas comunicações'),
         ('WhatsApp', 'Com DDI/DDD, ex.: +55 11 99999-0000'),
         ('Logo do clube', 'PNG ou JPG, máximo 2 MB (opcional)'),
       ],
       'after': 'Preencheu tudo? Clique em <b>Continuar</b>.'},
      {'h': 'Etapa 2 · Selecione as categorias',
       'b': 'Marque as categorias em que o clube pretende jogar: <b>Masculino, Feminino, Sub-15</b> e/ou <b>Sub-12</b> (pelo menos uma). Para cada categoria marcada, informe o <b>número estimado de atletas</b>. Clique em <b>Continuar</b>.'},
      {'h': 'Etapa 3 · Crie a senha e aceite os termos',
       'b': 'Defina uma senha com <b>no mínimo 8 caracteres</b> e confirme. Leia os Termos e Condições, marque <b>“Li e aceito os termos”</b> e clique em <b>Criar conta</b>.'},
      {'h': 'Confirme o e-mail',
       'b': 'Você receberá um e-mail de confirmação. Abra-o (verifique também a caixa de <b>spam</b>) e clique no link para <b>ativar a conta</b>. Sem essa confirmação, o cadastro não avança.'},
      {'h': 'Aguarde a aprovação da organização',
       'b': 'Após a verificação do e-mail, a organização analisa o cadastro. Você receberá um e-mail de aprovação — <b>só então o pagamento é liberado</b> no portal.'},
    ]},
    {'title': 'PARTE 2 — Entrar no portal do time', 'steps': [
      {'h': 'Faça login na Área dos Times',
       'b': 'Acesse <b>/portal/times/login</b> e entre com o <b>e-mail do responsável</b> (o mesmo do cadastro) e a senha. <b>Importante:</b> o login só é liberado depois que o e-mail foi confirmado <b>e</b> o cadastro foi aprovado pela organização.'},
      {'h': 'Se aparecer uma mensagem de erro, veja o que significa',
       'b': '<b>“E-mail não verificado”</b>: abra o e-mail de confirmação e clique no link (verifique o spam). · <b>“Cadastro aguardando aprovação”</b>: a organização ainda está analisando; aguarde o e-mail de aprovação. · <b>“Senha incorreta”</b>: confira a senha digitada. · <b>“Nenhuma conta encontrada”</b>: confira o e-mail — deve ser exatamente o usado no cadastro. · <b>Esqueceu a senha?</b> Clique em “Esqueci a senha” na tela de login, informe o e-mail do cadastro e siga o link enviado (vale por 1 hora) para criar uma nova senha.'},
      {'h': 'Conheça a tela inicial',
       'b': 'O portal abre na aba <b>Informações</b>, no idioma escolhido no cadastro. No topo ficam o nome e o logo do clube e o botão <b>Sair</b>. No celular, as abas aparecem na parte de baixo da tela.'},
      {'h': 'Aba Informações · Valores, prazos e vagas',
       'b': 'Reúne tudo o que o time precisa saber antes de pagar: janelas de confirmação (07/07 a 12/07 prioridade para pré-inscritos; 13/07 a 20/07 aberto a qualquer time), as duas opções de valores, o parcelamento, equipamentos exigidos e hospedagem/logística. <b>Atenção: as vagas por categoria são limitadas</b> e preenchidas por ordem de pagamento da 1ª parcela — quando a categoria lota, as inscrições encerram.'},
      {'h': 'Aba Inscrição · Acompanhe sua situação',
       'b': 'Mostra uma linha do tempo com as 5 etapas da inscrição — <b>Pré-inscrição → Pagamento → Inscrição confirmada → Inscrição de atletas → Aprovado</b> — com selos de “concluído” e “em andamento”, além dos dados do cadastro, das datas importantes e de um checklist de documentos para o time se organizar.'},
      {'h': 'Aba Pagamento · Pague a inscrição',
       'b': 'É onde você escolhe a forma de inscrição, acompanha as parcelas e paga com <b>Pix ou cartão</b>. Fica liberada após a aprovação — o passo a passo completo está na <b>Parte 3</b>.'},
      {'h': 'Aba Atletas · Monte o roster',
       'b': 'Cadastro dos atletas, acompanhamento por categoria e envio da escalação — detalhado na <b>Parte 4</b>.'},
      {'h': 'Aba Campeonato · Jogos e resultados',
       'b': 'Tabela de próximos jogos, resultados, estatísticas e pontuadores do seu time, ranking geral e mapa do venue em Leme, SP. Os horários dos jogos são divulgados após o fechamento das inscrições.'},
    ]},
    {'title': 'PARTE 3 — Pagar a inscrição', 'steps': [
      {'h': 'Abra a aba Pagamento',
       'b': 'Ela fica liberada depois que o cadastro é aprovado. Enquanto isso, a aba Inscrição mostra <b>“Aguardando aprovação da organização para liberar o pagamento”</b>.'},
      {'h': 'Escolha a forma de inscrição',
       'b': '<b>Opção 1 · Pacote:</b> R$ 2.000 por categoria, com atletas inclusos. · <b>Opção 2 · Por atleta:</b> R$ 800 por categoria + R$ 90 por atleta. Dá para trocar de opção livremente (botão <b>“Trocar opção”</b>) até o primeiro pagamento — depois ela fica travada.'},
      {'h': 'Na Opção 2, ajuste a quantidade de atletas',
       'b': 'Aparece um contador por categoria (botões + e −, R$ 90 por atleta). O total é recalculado na hora. Essa quantidade também fica travada após o primeiro pagamento.'},
      {'h': 'Confira o “Resumo da cobrança”',
       'b': 'O card no fim da aba mostra o detalhamento: categorias × valor da opção, atletas × R$ 90 (Opção 2) e o <b>total</b>. Confira antes de pagar.'},
      {'h': 'Entenda o parcelamento automático',
       'b': 'O plano é definido pela data do 1º pagamento: <b>até 20/07 → 3x · até 20/08 → 2x · depois → à vista</b>. Vencimentos: 20/07, 20/08 e 20/09/2026. As parcelas aparecem listadas com valor e vencimento, e cada uma tem seu próprio botão <b>Pagar</b>. <b>Atenção:</b> as vagas por categoria são garantidas pela ordem de pagamento da 1ª parcela — quem paga primeiro, garante a vaga.'},
      {'h': 'Para pagar com Pix',
       'b': 'Selecione <b>PIX</b>, clique em <b>Pagar</b> na parcela desejada e informe o CPF ou CNPJ do pagador (somente números; pedido uma única vez). Aparecem o QR Code e o código “copia e cola”. Pague no app do banco: assim que o Pix cair, <b>a página confirma sozinha</b> — não precisa enviar comprovante. Se o QR expirar, clique em “Novo QR”.'},
      {'h': 'Para pagar com cartão',
       'b': 'Selecione <b>Cartão de crédito</b>. As parcelas aparecem listadas como no Pix, cada uma com valor, vencimento e o próprio botão <b>Pagar</b>. Clique em <b>Pagar</b> na parcela desejada: você será redirecionado para o <b>checkout seguro da Stripe</b> e, ao concluir, volta ao portal — a confirmação aparece em instantes. Se preferir, pague algumas parcelas no Pix e outras no cartão.'},
      {'h': 'Acompanhe o status do pagamento',
       'b': 'O resumo mostra: <b>Aguardando pagamento → Pagamento em andamento</b> (com contador de parcelas pagas, ex.: 1/3) <b>→ ✓ Confirmado</b>. Lembre: <b>a 1ª parcela garante a vaga</b>; a inscrição é confirmada após a quitação total.'},
    ]},
    {'title': 'PARTE 4 — Cadastrar atletas e enviar a escalação', 'steps': [
      {'h': 'Adicione cada atleta',
       'b': 'Na aba Atletas, clique em <b>+ Atleta</b> e preencha: nome completo (obrigatório), nº da camisa, categoria, e-mail, data de nascimento e CPF/passaporte. Clique em <b>“Adicionar atleta”</b>.'},
      {'h': 'Sempre que possível, informe o e-mail do atleta',
       'b': 'Atleta cadastrado com e-mail recebe um <b>convite automático</b> para criar a própria conta no Portal do Atleta e completar o cadastro: foto de rosto, documento (RG/passaporte), histórico esportivo e aceite dos termos (direito de imagem e antidoping). O regulamento exige que o e-mail do atleta esteja na lista do clube.'},
      {'h': 'Acompanhe o painel por categoria',
       'b': 'Os cartões no topo mostram o total de atletas por categoria com código de cores: <b>verde ✓</b> ok (12–20) · <b>laranja ⚠</b> faltam atletas (mín. 12) · <b>vermelho ✕</b> excede o limite (máx. 20). Clique em um cartão para filtrar a lista por categoria. Categoria sem nenhum atleta é tratada como “não inscrita”. Além dos atletas, são permitidos até <b>7 staff/coaches</b> por categoria.'},
      {'h': 'Acompanhe a coluna “Portal” de cada atleta',
       'b': 'Ela mostra o andamento do cadastro individual: <b>Sem conta</b> (não iniciou) → <b>Verificar e-mail</b> (precisa clicar no link do convite) → perfil incompleto → <b>✓ Aprovado / Ativo</b>. Use essa coluna para cobrar os atletas pendentes antes do prazo.'},
      {'h': 'Edite ou remova quando precisar',
       'b': 'Use o botão ✎ para corrigir os dados de um atleta e o ✕ para excluir. Os contadores por categoria recalculam na hora.'},
      {'h': 'Envie a escalação',
       'b': 'Quando todas as categorias ativas estiverem com 12 a 20 atletas, o botão <b>“Enviar Escalação”</b> é liberado. Se aparecer <b>“Bloqueado”</b>, o aviso mostra exatamente o que falta em cada categoria (ex.: “Feminino: 9/12, faltam 3”). Apenas times aprovados conseguem enviar. <b>Prazo final: 30/09/2026</b>.'},
      {'h': 'Depois do envio',
       'b': 'Aparece a confirmação <b>“Escalação enviada!”</b> e a organização recebe o roster completo. Precisa alterar algo depois do envio? Fale com a organização pelo e-mail ou WhatsApp do rodapé.'},
    ]},
  ],
  'dates_title': 'DATAS IMPORTANTES',
  'dates': [
    ('20/07', '1ª parcela do pagamento de inscrição'),
    ('20/08', '2ª parcela do pagamento de inscrição'),
    ('20/09', '3ª parcela do pagamento de inscrição'),
    ('30/09', 'Aprovação de documentos dos atletas e prazo do roster completo'),
    ('31/10', 'Cerimônia de abertura e início da fase de grupos'),
  ],
  'checklist_title': 'CHECKLIST FINAL DO TIME',
  'checklist': [
    'Conta criada, e-mail confirmado e cadastro aprovado',
    'Pagamento da taxa de inscrição confirmado (todas as parcelas)',
    'Roster completo enviado (12–20 atletas por categoria)',
    'Documentos de identificação de todos os atletas (RG/passaporte)',
    'Uniformes em conformidade: 2 jogos de camisas numeradas (claro e escuro), calções sem bolsos, cleats de borracha',
  ],
},
# ══════════════════════════════ ES ══════════════════════════════
'es': {
  'filename': 'Guia-de-Inscripcion-de-Equipos-BFWC2026-ES.pdf',
  'title': 'Guía de Inscripción de Equipos',
  'subtitle': 'Brasil Flag World Championship 2026 · Paso a paso completo, desde la cuenta hasta el envío de la alineación',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP — Brasil · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'PLAZOS DE INSCRIPCIÓN',
  'deadlines_body': 'Del <b>07/07 al 12/07</b>, la inscripción es exclusiva para equipos <b>ya pre-inscritos</b> — usa el <b>mismo correo</b> informado en la pre-inscripción. A partir del <b>13/07</b>, queda abierta para cualquier equipo. <b>Plazas limitadas:</b> las plazas por categoría se llenan por orden de inscripción y reserva — asegura su lugar quien paga la 1.ª cuota primero. Cuando la categoría se llena, las inscripciones cierran.',
  'contact': '¿Dudas? Correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'RESUMEN — LÍNEA DE TIEMPO DE LA INSCRIPCIÓN',
  'timeline': [
    ('1', 'Registro del club', '07/07 al 12/07 — pre-inscritos · desde el 13/07 — abierto a todos'),
    ('2', 'Elección de las categorías', 'Al crear la cuenta (Etapa 2 del registro)'),
    ('3', 'Pago de la 1.ª cuota — <b>asegura la plaza</b>', 'Hasta el <b>20/07</b> · plazas llenadas por los pagos efectuados primero'),
    ('4', 'Pago de las cuotas restantes', '2.ª hasta el 20/08 · 3.ª hasta el 20/09'),
    ('5', 'Registro de los atletas', 'Hasta el 30/09'),
    ('6', 'Envío de la alineación', 'Hasta el 30/09'),
    ('✓', '<b>¡Inscripción finalizada!</b>', 'Nos vemos en Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Crear la cuenta del club', 'steps': [
      {'h': 'Accede a la página de registro',
       'b': 'Entra en <b>www.brasilflagworldchampionship.com</b>, ve al <b>Portal</b> y elige <b>Registro de Club</b> (o accede directo a <b>/portal/times/cadastro</b>). Funciona en el móvil y en la computadora.'},
      {'h': 'Elige el idioma',
       'b': 'En la primera pantalla, selecciona <b>Português</b>, <b>English</b> o <b>Español</b>. Todo el portal seguirá tu elección.'},
      {'h': 'Etapa 1 · Completa los datos del club',
       'b': '<b>Este registro se utilizará durante todo el campeonato.</b> Los campos marcados con * son obligatorios:',
       'table': [
         ('Nombre del club *', 'Nombre oficial del club/organización'),
         ('País * y Ciudad', 'Selecciona el país de la lista; la ciudad es opcional'),
         ('Nombre del responsable *', 'Persona de contacto del club'),
         ('Cargo / Función', 'Ej.: presidente, entrenador (opcional)'),
         ('Correo electrónico *', 'Se usará en el login y en las comunicaciones'),
         ('WhatsApp', 'Con código de país, ej.: +52 55 5555-0100'),
         ('Logo del club', 'PNG o JPG, máximo 2 MB (opcional)'),
       ],
       'after': '¿Todo listo? Haz clic en <b>Continuar</b>.'},
      {'h': 'Etapa 2 · Selecciona las categorías',
       'b': 'Marca las categorías en las que el club planea participar: <b>Masculino, Femenino (Feminino), Sub-15</b> y/o <b>Sub-12</b> (al menos una). Para cada categoría, indica el <b>número estimado de atletas</b>. Haz clic en <b>Continuar</b>.'},
      {'h': 'Etapa 3 · Crea la contraseña y acepta los términos',
       'b': 'Define una contraseña de <b>mínimo 8 caracteres</b> y confírmala. Lee los Términos y Condiciones, marca <b>“He leído y acepto los términos”</b> y haz clic en <b>Crear cuenta</b>.'},
      {'h': 'Confirma tu correo',
       'b': 'Recibirás un correo de confirmación. Ábrelo (revisa también el <b>spam</b>) y haz clic en el enlace para <b>activar tu cuenta</b>. Sin esta confirmación, el registro no avanza.'},
      {'h': 'Espera la aprobación de la organización',
       'b': 'Tras la verificación del correo, la organización revisa el registro. Recibirás un correo de aprobación — <b>solo entonces se libera el pago</b> en el portal.'},
    ]},
    {'title': 'PARTE 2 — Entrar al portal del equipo', 'steps': [
      {'h': 'Inicia sesión en el Área de Equipos',
       'b': 'Accede a <b>/portal/times/login</b> con el <b>correo del responsable</b> (el mismo del registro) y tu contraseña. <b>Importante:</b> el login solo funciona después de que el correo fue confirmado <b>y</b> el registro fue aprobado por la organización.'},
      {'h': 'Si aparece un mensaje de error, esto es lo que significa',
       'b': '<b>“Correo no verificado”</b>: abre el correo de confirmación y haz clic en el enlace (revisa el spam). · <b>“Registro esperando aprobación”</b>: la organización aún está revisando; espera el correo de aprobación. · <b>“Contraseña incorrecta”</b>: revisa lo que escribiste. · <b>“Ninguna cuenta encontrada”</b>: verifica el correo — debe ser exactamente el usado en el registro. · <b>¿Olvidaste la contraseña?</b> Haz clic en “Olvidé mi contraseña” en la pantalla de login, ingresa el correo del registro y sigue el enlace enviado (vale por 1 hora) para crear una nueva contraseña.'},
      {'h': 'Conoce la pantalla inicial',
       'b': 'El portal abre en la pestaña <b>Información</b>, en el idioma elegido en el registro. Arriba verás el nombre y el logo del club y el botón <b>Salir</b>. En el móvil, las pestañas aparecen en la parte inferior de la pantalla.'},
      {'h': 'Pestaña Información · Valores, plazos y plazas',
       'b': 'Todo lo que el equipo necesita saber antes de pagar: ventanas de confirmación (07/07 al 12/07 prioridad para pre-inscritos; 13/07 al 20/07 abierto a cualquier equipo), las dos opciones de valores, las cuotas, el equipamiento exigido y alojamiento/logística. <b>Atención: las plazas por categoría son limitadas</b> y se llenan por orden de pago de la 1.ª cuota — cuando la categoría se llena, las inscripciones se cierran.'},
      {'h': 'Pestaña Inscripción · Sigue tu estado',
       'b': 'Muestra una línea de tiempo con las 5 etapas de la inscripción — <b>Pre-inscripción → Pago → Inscripción confirmada → Inscripción de atletas → Aprobado</b> — con sellos de “completado” y “en curso”, además de los datos del registro, las fechas importantes y un checklist de documentos para organizar al equipo.'},
      {'h': 'Pestaña Pago · Paga la inscripción',
       'b': 'Ahí eliges la forma de inscripción, sigues las cuotas y pagas con <b>tarjeta de crédito</b> (o transferencia Wise). Se libera tras la aprobación — el paso a paso completo está en la <b>Parte 3</b>.'},
      {'h': 'Pestaña Atletas · Arma el roster',
       'b': 'Registro de atletas, seguimiento por categoría y envío de la alineación — detallado en la <b>Parte 4</b>.'},
      {'h': 'Pestaña Campeonato · Partidos y resultados',
       'b': 'Calendario de próximos partidos, resultados, estadísticas y anotadores de tu equipo, ranking general y mapa del venue en Leme, SP. Los horarios se publican tras el cierre de las inscripciones.'},
    ]},
    {'title': 'PARTE 3 — Pagar la inscripción', 'steps': [
      {'h': 'Abre la pestaña Pago',
       'b': 'Se libera cuando el registro es aprobado. Mientras tanto, la pestaña Inscripción muestra <b>“Esperando la aprobación de la organización para liberar el pago”</b>.'},
      {'h': 'Elige la forma de inscripción',
       'b': '<b>Opción 1 · Paquete:</b> R$ 2.000 por categoría, con atletas incluidos. · <b>Opción 2 · Por atleta:</b> R$ 800 por categoría + R$ 90 por atleta. Puedes cambiar libremente (botón <b>“Cambiar opción”</b>) hasta el primer pago — después queda bloqueada.'},
      {'h': 'En la Opción 2, ajusta la cantidad de atletas',
       'b': 'Aparece un contador por categoría (botones + y −, R$ 90 por atleta). El total se recalcula al instante. Esta cantidad también queda bloqueada tras el primer pago.'},
      {'h': 'Revisa el “Resumen del cobro”',
       'b': 'La tarjeta al final de la pestaña muestra el detalle: categorías × valor de la opción, atletas × R$ 90 (Opción 2) y el <b>total</b>. Revísalo antes de pagar.'},
      {'h': 'Entiende las cuotas automáticas',
       'b': 'El plan depende de la fecha del primer pago: <b>hasta el 20/07 → 3 cuotas · hasta el 20/08 → 2 · después → pago único</b>. Vencimientos: 20/07, 20/08 y 20/09/2026. Las cuotas aparecen listadas con monto y vencimiento, cada una con su propio botón <b>Pagar</b>. <b>Atención:</b> las plazas por categoría se garantizan por orden de pago de la 1.ª cuota — quien paga primero, asegura su lugar.'},
      {'h': 'Para pagar con tarjeta',
       'b': 'Selecciona <b>Tarjeta de crédito</b>. Las cuotas aparecen listadas con monto, vencimiento y su propio botón <b>Pagar</b>. Haz clic en <b>Pagar</b> en la cuota deseada: serás redirigido al <b>checkout seguro de Stripe</b> y, al terminar, vuelves al portal — la confirmación aparece en instantes. Se aceptan tarjetas internacionales; el cobro es en reales (BRL) y tu banco hace la conversión a tu moneda.'},
      {'h': 'Para pagar por transferencia (Wise)',
       'b': '¿Prefieres una transferencia internacional? La organización acepta <b>Wise</b>. Contacta a <b>Leonardo</b> — correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 81 99565-8710</b> — para coordinar la transferencia y confirmar tus cuotas en el portal.'},
      {'h': 'Sigue el estado del pago',
       'b': 'El resumen muestra: <b>Esperando pago → Pago en curso</b> (con contador de cuotas pagadas, ej.: 1/3) <b>→ ✓ Confirmado</b>. Recuerda: <b>la 1.ª cuota asegura la plaza</b>; la inscripción se confirma tras el pago total.'},
    ]},
    {'title': 'PARTE 4 — Registrar atletas y enviar la alineación', 'steps': [
      {'h': 'Agrega a cada atleta',
       'b': 'En la pestaña Atletas, haz clic en <b>+ Atleta</b> y completa: nombre completo (obligatorio), n.º de camiseta, categoría, correo, fecha de nacimiento y CPF/pasaporte. Haz clic en <b>“Agregar atleta”</b>.'},
      {'h': 'Siempre que puedas, informa el correo del atleta',
       'b': 'Cada atleta agregado con correo recibe una <b>invitación automática</b> para crear su propia cuenta en el Portal del Atleta y completar su registro: foto de rostro, documento (ID/pasaporte), historial deportivo y aceptación de los términos (derechos de imagen y antidopaje). El reglamento exige que el correo del atleta esté en la lista del club.'},
      {'h': 'Sigue el panel por categoría',
       'b': 'Las tarjetas de arriba muestran el total de atletas por categoría con código de colores: <b>verde ✓</b> ok (12–20) · <b>naranja ⚠</b> faltan atletas (mín. 12) · <b>rojo ✕</b> excede el límite (máx. 20). Haz clic en una tarjeta para filtrar la lista por categoría. Una categoría sin atletas se trata como “no inscrita”. Además de los atletas, se permiten hasta <b>7 staff/entrenadores</b> por categoría.'},
      {'h': 'Sigue la columna “Portal” de cada atleta',
       'b': 'Muestra el avance del registro individual: <b>Sin cuenta</b> (no empezó) → <b>Verificar correo</b> (debe hacer clic en el enlace de la invitación) → perfil incompleto → <b>✓ Aprobado / Activo</b>. Usa esta columna para reclamar a los atletas pendientes antes del plazo.'},
      {'h': 'Edita o elimina cuando haga falta',
       'b': 'Usa el botón ✎ para corregir los datos de un atleta y ✕ para eliminarlo. Los contadores por categoría se recalculan al instante.'},
      {'h': 'Envía la alineación',
       'b': 'Cuando todas las categorías activas tengan de 12 a 20 atletas, se libera el botón <b>“Enviar Alineación”</b>. Si aparece <b>“Bloqueado”</b>, el aviso indica exactamente qué falta en cada categoría (ej.: “Femenino: 9/12, faltan 3”). Solo los equipos aprobados pueden enviar. <b>Fecha límite: 30/09/2026</b>.'},
      {'h': 'Después del envío',
       'b': 'Verás la confirmación <b>“¡Alineación enviada!”</b> y la organización recibe el roster completo. ¿Necesitas cambiar algo después del envío? Contacta a la organización por el correo o WhatsApp del pie de página.'},
    ]},
  ],
  'dates_title': 'FECHAS IMPORTANTES',
  'dates': [
    ('20/07', '1.ª cuota del pago de inscripción'),
    ('20/08', '2.ª cuota del pago de inscripción'),
    ('20/09', '3.ª cuota del pago de inscripción'),
    ('30/09', 'Aprobación de documentos de los atletas y plazo del roster completo'),
    ('31/10', 'Ceremonia de apertura e inicio de la fase de grupos'),
  ],
  'checklist_title': 'CHECKLIST FINAL DEL EQUIPO',
  'checklist': [
    'Cuenta creada, correo confirmado y registro aprobado',
    'Pago de la inscripción confirmado (todas las cuotas)',
    'Roster completo enviado (12–20 atletas por categoría)',
    'Documentos de identificación de todos los atletas (ID/pasaporte)',
    'Uniformes conformes: 2 juegos de camisetas numeradas (clara y oscura), shorts sin bolsillos, tacos de goma',
  ],
},
# ══════════════════════════════ EN ══════════════════════════════
'en': {
  'filename': 'Team-Registration-Guide-BFWC2026-EN.pdf',
  'title': 'Team Registration Guide',
  'subtitle': 'Brasil Flag World Championship 2026 · Complete step-by-step, from account creation to lineup submission',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP — Brazil · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'REGISTRATION DEADLINES',
  'deadlines_body': 'From <b>Jul 7 to Jul 12</b>, registration is exclusive to <b>pre-registered teams</b> — use the <b>same email</b> from your pre-registration. From <b>Jul 13</b>, registration opens to any team. <b>Limited spots:</b> spots per category are filled in order of registration and reservation — the spot goes to whoever pays the 1st installment first. Once a category is full, registration closes.',
  'contact': 'Questions? Email <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'SUMMARY — REGISTRATION TIMELINE',
  'timeline': [
    ('1', 'Club registration', 'Jul 7–12 — pre-registered · from Jul 13 — open to all'),
    ('2', 'Category selection', 'During account creation (Step 2)'),
    ('3', '1st installment payment — <b>secures your spot</b>', 'By <b>Jul 20</b> · spots filled by earliest payments first'),
    ('4', 'Remaining installments', '2nd by Aug 20 · 3rd by Sep 20'),
    ('5', 'Athlete registration', 'By Sep 30'),
    ('6', 'Lineup submission', 'By Sep 30'),
    ('✓', '<b>Registration complete!</b>', 'See you in Leme, SP — Oct 31'),
  ],
  'parts': [
    {'title': 'PART 1 — Create your club account', 'steps': [
      {'h': 'Open the registration page',
       'b': 'Go to <b>www.brasilflagworldchampionship.com</b>, open the <b>Portal</b> and choose <b>Club Registration</b> (or go directly to <b>/portal/times/cadastro</b>). Works on mobile and desktop.'},
      {'h': 'Choose your language',
       'b': 'On the first screen, select <b>Português</b>, <b>English</b> or <b>Español</b>. The whole portal will follow your choice.'},
      {'h': 'Step 1 · Fill in the club details',
       'b': '<b>This registration will be used throughout the entire championship.</b> Fields marked with * are required:',
       'table': [
         ('Club name *', 'Official name of the club/organization'),
         ('Country * and City', 'Select the country from the list; city is optional'),
         ('Contact name *', 'Club contact person'),
         ('Role / Position', 'E.g. president, head coach (optional)'),
         ('Email *', 'Used for login and all communications'),
         ('WhatsApp', 'With country code, e.g. +1 305 555-0100'),
         ('Club logo', 'PNG or JPG, max 2 MB (optional)'),
       ],
       'after': 'All set? Click <b>Continue</b>.'},
      {'h': 'Step 2 · Select your categories',
       'b': "Check the categories your club plans to enter: <b>Men (Masculino), Women (Feminino), U-15 (Sub-15)</b> and/or <b>U-12 (Sub-12)</b> — at least one. For each category, enter the <b>estimated number of athletes</b>. Click <b>Continue</b>."},
      {'h': 'Step 3 · Create a password and accept the terms',
       'b': 'Set a password with <b>at least 8 characters</b> and confirm it. Read the Terms and Conditions, check <b>“I have read and accept the terms”</b> and click <b>Create account</b>.'},
      {'h': 'Confirm your email',
       'b': 'You will receive a confirmation email. Open it (check your <b>spam</b> folder too) and click the link to <b>activate your account</b>. Registration cannot proceed without this step.'},
      {'h': 'Wait for organization approval',
       'b': 'After email verification, the organization reviews your registration. You will receive an approval email — <b>only then is payment unlocked</b> in the portal.'},
    ]},
    {'title': 'PART 2 — Access the team portal', 'steps': [
      {'h': 'Log in to the Team Area',
       'b': 'Go to <b>/portal/times/login</b> and sign in with the <b>contact email</b> (the same one used at registration) and your password. <b>Important:</b> login only works after your email has been confirmed <b>and</b> your registration has been approved by the organization.'},
      {'h': 'If you see an error message, here is what it means',
       'b': '<b>“Email not verified”</b>: open the confirmation email and click the link (check spam). · <b>“Registration awaiting approval”</b>: the organization is still reviewing; wait for the approval email. · <b>“Wrong password”</b>: double-check what you typed. · <b>“No account found”</b>: check the email — it must be exactly the one used at registration. · <b>Forgot your password?</b> Click “Forgot my password” on the login screen, enter your registration email and follow the emailed link (valid for 1 hour) to create a new password.'},
      {'h': 'Get to know the home screen',
       'b': 'The portal opens on the <b>Information</b> tab, in the language chosen at registration. At the top you will see your club name and logo and the <b>Log out</b> button. On mobile, the tabs appear at the bottom of the screen.'},
      {'h': 'Information tab · Prices, deadlines and spots',
       'b': 'Everything the team needs to know before paying: confirmation windows (Jul 7–12 priority for pre-registered teams; Jul 13–20 open to any team), both pricing options, installments, required equipment and accommodation/logistics. <b>Attention: spots per category are limited</b> and filled in order of payment of the 1st installment — once a category is full, registration closes.'},
      {'h': 'Registration tab · Track your status',
       'b': 'Shows a timeline with the 5 registration stages — <b>Pre-registration → Payment → Registration confirmed → Athlete registration → Approved</b> — with “done” and “in progress” badges, plus your registration details, the important dates and a document checklist to keep the team organized.'},
      {'h': 'Payment tab · Pay the registration fee',
       'b': 'Where you choose your registration option, track installments and pay by <b>credit card</b> (or Wise transfer). Unlocked after approval — the full walkthrough is in <b>Part 3</b>.'},
      {'h': 'Athletes tab · Build the roster',
       'b': 'Athlete registration, per-category tracking and lineup submission — detailed in <b>Part 4</b>.'},
      {'h': 'Championship tab · Games and results',
       'b': 'Schedule of upcoming games, results, your team\'s stats and scorers, overall ranking and the venue map in Leme, SP. Game times are published after registration closes.'},
    ]},
    {'title': 'PART 3 — Pay the registration fee', 'steps': [
      {'h': 'Open the Payment tab',
       'b': 'It is unlocked once your registration is approved. Until then, the Registration tab shows <b>“Awaiting organization approval to unlock payment”</b>.'},
      {'h': 'Choose your registration option',
       'b': '<b>Option 1 · Package:</b> R$ 2,000 per category, athletes included. · <b>Option 2 · Per athlete:</b> R$ 800 per category + R$ 90 per athlete. You can switch freely (<b>“Change option”</b> button) until the first payment — after that it is locked.'},
      {'h': 'On Option 2, set the number of athletes',
       'b': 'A counter appears for each category (+ and − buttons, R$ 90 per athlete). The total recalculates instantly. This quantity is also locked after the first payment.'},
      {'h': 'Check the “Charge summary”',
       'b': 'The card at the bottom of the tab shows the breakdown: categories × option price, athletes × R$ 90 (Option 2) and the <b>total</b>. Review it before paying.'},
      {'h': 'Understand the automatic installments',
       'b': 'The plan depends on the date of your first payment: <b>by Jul 20 → 3 installments · by Aug 20 → 2 · after that → single payment</b>. Due dates: Jul 20, Aug 20 and Sep 20, 2026. Installments are listed with amount and due date, each with its own <b>Pay</b> button. <b>Attention:</b> spots per category are secured in order of payment of the 1st installment — pay first, secure your spot.'},
      {'h': 'To pay by card',
       'b': 'Select <b>Credit card</b>. Installments are listed with amount, due date and their own <b>Pay</b> button. Click <b>Pay</b> on the desired installment: you are redirected to the <b>secure Stripe checkout</b> and, once done, you return to the portal — confirmation appears within moments. International cards are accepted; charges are in Brazilian reais (BRL) and your bank converts to your currency.'},
      {'h': 'To pay by bank transfer (Wise)',
       'b': 'Prefer an international bank transfer? The organization accepts <b>Wise</b>. Contact <b>Leonardo</b> — email <b>contato@brasilflag.com</b> · WhatsApp <b>+55 81 99565-8710</b> — to arrange the transfer and have your installments confirmed in the portal.'},
      {'h': 'Track the payment status',
       'b': 'The summary shows: <b>Awaiting payment → Payment in progress</b> (with a paid-installments counter, e.g. 1/3) <b>→ ✓ Confirmed</b>. Remember: <b>the 1st installment secures your spot</b>; registration is confirmed after full payment.'},
    ]},
    {'title': 'PART 4 — Register athletes and submit the lineup', 'steps': [
      {'h': 'Add each athlete',
       'b': 'In the Athletes tab, click <b>+ Athlete</b> and fill in: full name (required), jersey number, category, email, date of birth and tax ID/passport. Click <b>“Add athlete”</b>.'},
      {'h': "Whenever possible, enter the athlete's email",
       'b': 'Every athlete added with an email receives an <b>automatic invitation</b> to create their own account on the Athlete Portal and complete their registration: face photo, ID document (ID card/passport), sports history and acceptance of the terms (image rights and anti-doping). The rules require the athlete\'s email to be on the club roster.'},
      {'h': 'Track the per-category panel',
       'b': 'The cards at the top show the athlete count per category, color-coded: <b>green ✓</b> ok (12–20) · <b>orange ⚠</b> athletes missing (min. 12) · <b>red ✕</b> over the limit (max. 20). Click a card to filter the list by category. A category with no athletes is treated as “not entered”. Besides athletes, up to <b>7 staff/coaches</b> per category are allowed.'},
      {'h': "Track each athlete's “Portal” column",
       'b': 'It shows each individual registration status: <b>No account</b> (not started) → <b>Verify email</b> (needs to click the invite link) → incomplete profile → <b>✓ Approved / Active</b>. Use this column to chase pending athletes before the deadline.'},
      {'h': 'Edit or remove whenever needed',
       'b': "Use the ✎ button to fix an athlete's details and ✕ to delete. The category counters recalculate instantly."},
      {'h': 'Submit the lineup',
       'b': 'When every active category has 12 to 20 athletes, the <b>“Submit Lineup”</b> button is unlocked. If it shows <b>“Blocked”</b>, the notice tells you exactly what is missing in each category (e.g. “Women: 9/12, 3 missing”). Only approved teams can submit. <b>Final deadline: Sep 30, 2026</b>.'},
      {'h': 'After submitting',
       'b': 'You will see the <b>\u201cLineup submitted!\u201d</b> confirmation and the organization receives the full roster. Need to change something after submitting? Contact the organization via the email or WhatsApp in the footer.'},
    ]},
  ],
  'dates_title': 'IMPORTANT DATES',
  'dates': [
    ('Jul 20', 'Registration fee \u2014 1st installment'),
    ('Aug 20', 'Registration fee \u2014 2nd installment'),
    ('Sep 20', 'Registration fee \u2014 3rd installment'),
    ('Sep 30', 'Athlete document approval and full roster deadline'),
    ('Oct 31', 'Opening ceremony and start of the group stage'),
  ],
  'checklist_title': 'FINAL TEAM CHECKLIST',
  'checklist': [
    'Account created, email confirmed and registration approved',
    'Registration fee payment confirmed (all installments)',
    'Full roster submitted (12\u201320 athletes per category)',
    'ID documents for all athletes (ID card/passport)',
    'Uniforms compliant: 2 sets of numbered jerseys (light and dark), shorts without pockets, rubber cleats',
  ],
},
}
