# -*- coding: utf-8 -*-
# v2
"""Conteúdo dos guias ILUSTRADOS (PT/ES/EN) — BFWC 2026.

Cada passo: h = título, b = corpo (markup <b>), img = screenshot (opcional),
cap = legenda da imagem (opcional).
Setas amarelas: use arrow.py para anotar novos screenshots antes de referenciá-los.
"""

ILU = {
# ══════════════════════════════ PT ══════════════════════════════
'pt': {
  'filename': 'Guia-Ilustrado-Inscricao-Times-BFWC2026-PT.pdf',
  'title': 'Guia Ilustrado de Inscrição dos Times',
  'subtitle': 'Brasil Flag World Championship 2026 · Passo a passo com imagens, da criação da conta ao envio da escalação',
  'footer': 'Guia Ilustrado de Inscrição dos Times · BFWC 2026 · página {n}',
  'deadlines_title': 'PRAZOS DE INSCRIÇÃO',
  'deadlines_body': 'De <b>07/07 a 12/07</b>, a inscrição é exclusiva para times já pré-inscritos — use o mesmo e-mail informado na pré-inscrição. A partir de <b>13/07</b>, o cadastro fica aberto para qualquer time.<br/><b>Vagas limitadas:</b> as vagas por categoria são preenchidas por ordem de inscrição e reserva — garante a vaga quem paga a 1ª parcela primeiro. Quando a categoria lota, as inscrições encerram.<br/>Dúvidas? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>Como usar este guia:</b> as setas amarelas nas imagens mostram exatamente onde clicar em cada passo.',
  'timeline_title': 'RESUMO — LINHA DO TEMPO DA INSCRIÇÃO',
  'timeline': [
    ('1', 'Cadastro do clube', '07/07 a 12/07 — pré-inscritos · a partir de 13/07 — aberto a todos'),
    ('2', 'Escolha das categorias', 'Na criação da conta (Etapa 2 do cadastro)'),
    ('3', 'Pagamento da 1ª parcela — <b>garante a vaga</b>', 'Até <b>20/07</b> · vagas preenchidas pelos pagamentos efetuados primeiro'),
    ('4', 'Pagamento das parcelas restantes', '2ª até 20/08 · 3ª até 20/09'),
    ('5', 'Inscrição dos atletas', 'Até 30/09'),
    ('6', 'Envio da escalação', 'Até 30/09'),
    ('✓', '<b>Inscrição finalizada!</b>', 'Nos vemos em Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Criar a conta do clube', 'steps': [
      {'h': '1. Acesse o site e clique em “Cadastrar Minha Equipe”',
       'b': 'Entre em <b>www.brasilflagworldchampionship.com</b>. Na página inicial, clique no botão amarelo <b>Cadastrar Minha Equipe</b> (indicado pela seta) ou vá em Portal → Cadastro de Clube. Funciona no celular e no computador.',
       'img': 'img/pt/01-home.png', 'cap': 'A seta indica o botão “Cadastrar Minha Equipe” na página inicial.'},
      {'h': '2. Escolha o idioma',
       'b': 'Na primeira tela, selecione <b>Português</b>, English ou Español. Todo o portal seguirá o idioma escolhido.',
       'img': 'img/pt/02-cadastro-idioma.png', 'cap': 'Clique em “Entrar em Português” para seguir o cadastro em PT-BR.'},
      {'h': '3. Etapa 1 · Preencha os dados do clube',
       'b': '<b>Esse cadastro será utilizado durante todo o campeonato.</b> Campos marcados com * são obrigatórios: <b>Nome do clube*</b>, <b>País*</b> e Cidade, <b>Nome do responsável*</b>, Cargo/Função, <b>E-mail*</b> (será usado no login e nas comunicações), WhatsApp (com DDI/DDD) e o Logo do clube (PNG ou JPG, máx. 2 MB, opcional).',
       'img': 'img/pt/03-etapa1-dados.png', 'cap': 'Formulário da Etapa 1 — comece pelo Nome do clube.'},
      {'h': '4. Clique em “Continuar”',
       'b': 'Preencheu tudo? Clique no botão azul <b>Continuar</b> no fim do formulário.',
       'img': 'img/pt/04-continuar.png', 'cap': 'O botão Continuar fica logo abaixo do campo de logo.'},
      {'h': '5. Etapa 2 · Selecione as categorias',
       'b': 'Marque as categorias em que o clube pretende jogar: <b>Masculino, Feminino, Sub-15</b> e/ou <b>Sub-12</b> (pelo menos uma).',
       'img': 'img/pt/05-categorias.png', 'cap': 'Clique nos cartões para marcar as categorias desejadas.'},
      {'h': '6. Informe o número estimado de atletas',
       'b': 'Para cada categoria marcada, aparece um campo <b>Nº de atletas</b>. Preencha a estimativa e clique em <b>Continuar</b>.',
       'img': 'img/pt/06-num-atletas.png', 'cap': 'Com as categorias marcadas, informe o nº de atletas e clique em Continuar.'},
      {'h': '7. Etapa 3 · Crie a senha',
       'b': 'Defina uma senha com <b>no mínimo 8 caracteres</b> e repita no campo de confirmação.',
       'img': 'img/pt/07-senha.png', 'cap': 'Campos de senha e confirmação na Etapa 3.'},
      {'h': '8. Aceite os termos e clique em “Criar Conta”',
       'b': 'Leia os Termos e Condições, marque <b>“Li e aceito os termos e condições”</b> (seta da esquerda) e clique em <b>Criar Conta</b> (seta da direita).',
       'img': 'img/pt/08-termos-criar-conta.png', 'cap': 'Marque o aceite dos termos e finalize em Criar Conta.'},
      {'h': '9. Confirme o e-mail',
       'b': 'Você receberá um e-mail de confirmação. Abra-o (verifique também a caixa de <b>spam</b>) e clique no link para <b>ativar a conta</b>. Sem essa confirmação, o cadastro não avança.'},
      {'h': '10. Aguarde a aprovação da organização',
       'b': 'Após a verificação do e-mail, a organização analisa o cadastro. Você receberá um e-mail de aprovação — <b>só então o pagamento é liberado</b> no portal.'},
    ]},
    {'title': 'PARTE 2 — Entrar no portal do time', 'steps': [
      {'h': '1. Acesse a Área dos Times e escolha o idioma',
       'b': 'Acesse <b>/portal/times/login</b>. A primeira tela pede o idioma — clique em <b>Entrar em Português</b>.',
       'img': 'img/pt/09-login-idioma.png', 'cap': 'Tela de idioma da Área dos Times.'},
      {'h': '2. Faça login',
       'b': 'Entre com o <b>e-mail do responsável</b> (o mesmo do cadastro) e a senha, e clique em <b>Entrar na Área do Clube</b>. Importante: o login só é liberado depois que o e-mail foi confirmado e o cadastro foi aprovado pela organização. Esqueceu a senha? Clique em <b>“Esqueci a senha”</b>, logo acima do botão.',
       'img': 'img/pt/10-login.png', 'cap': 'A seta indica o botão de login. O link “Esqueci a senha” fica logo acima.'},
      {'h': '3. Se aparecer uma mensagem de erro, veja o que significa',
       'b': '<b>“E-mail não verificado”</b>: abra o e-mail de confirmação e clique no link (verifique o spam). · <b>“Cadastro aguardando aprovação”</b>: a organização ainda está analisando; aguarde o e-mail de aprovação. · <b>“Senha incorreta”</b>: confira a senha digitada. · <b>“Nenhuma conta encontrada”</b>: confira o e-mail — deve ser exatamente o usado no cadastro. · O link de redefinição de senha vale por 1 hora.'},
      {'h': '4. Conheça a tela inicial',
       'b': 'O portal abre na aba <b>Informações</b>, no idioma escolhido no cadastro. No topo ficam o nome e o logo do clube e o botão <b>Sair</b>. No celular, as abas aparecem na parte de baixo da tela.'},
      {'h': '5. Aba Informações · Valores, prazos e vagas',
       'b': 'Reúne tudo o que o time precisa saber antes de pagar: janelas de confirmação (07/07 a 12/07 prioridade para pré-inscritos; 13/07 a 20/07 aberto a qualquer time), as duas opções de valores, o parcelamento, equipamentos exigidos e hospedagem/logística. <b>Atenção: as vagas por categoria são limitadas</b> e preenchidas por ordem de pagamento da 1ª parcela — quando a categoria lota, as inscrições encerram.'},
      {'h': '6. Aba Inscrição · Acompanhe sua situação',
       'b': 'Mostra uma linha do tempo com as 5 etapas da inscrição — <b>Pré-inscrição → Pagamento → Inscrição confirmada → Inscrição de atletas → Aprovado</b> — com selos de “concluído” e “em andamento”, além dos dados do cadastro, das datas importantes e de um checklist de documentos para o time se organizar.'},
      {'h': '7. Aba Pagamento · Pague a inscrição',
       'b': 'É onde você escolhe a forma de inscrição, acompanha as parcelas e paga com <b>Pix ou cartão</b>. Fica liberada após a aprovação — o passo a passo completo está na <b>Parte 3</b>.'},
      {'h': '8. Aba Atletas · Monte o roster',
       'b': 'Cadastro dos atletas, acompanhamento por categoria e envio da escalação — detalhado na <b>Parte 4</b>.'},
      {'h': '9. Aba Campeonato · Jogos e resultados',
       'b': 'Tabela de próximos jogos, resultados, estatísticas e pontuadores do seu time, ranking geral e mapa do venue em Leme, SP. Os horários dos jogos são divulgados após o fechamento das inscrições.'},
    ]},
    {'title': 'PARTE 3 — Pagar a inscrição', 'steps': [
      {'h': '1. Abra a aba Pagamento',
       'b': 'Ela fica liberada depois que o cadastro é aprovado. Enquanto isso, a aba Inscrição mostra <b>“Aguardando aprovação da organização para liberar o pagamento”</b>.'},
      {'h': '2. Escolha a forma de inscrição',
       'b': '<b>Opção 1 · Pacote:</b> R$ 2.000 por categoria, com atletas inclusos. · <b>Opção 2 · Por atleta:</b> R$ 800 por categoria + R$ 90 por atleta. Dá para trocar de opção livremente (botão <b>“Trocar opção”</b>) até o primeiro pagamento — depois ela fica travada.',
       'img': 'img/pt/11-pagamento-opcao.png', 'cap': 'Escolha entre Opção 1 · Pacote e Opção 2 · Por atleta.'},
      {'h': '3. Na Opção 2, ajuste a quantidade de atletas',
       'b': 'Aparece um contador por categoria (botões + e −, R$ 90 por atleta). O total é recalculado na hora. Essa quantidade também fica travada após o primeiro pagamento.',
       'img': 'img/pt/21-opcao2-contador.png', 'cap': 'Na Opção 2, ajuste a quantidade de atletas por categoria com os botões + e −.'},
      {'h': '4. Confira o “Resumo da cobrança”',
       'b': 'O card no fim da aba mostra o detalhamento: categorias × valor da opção, atletas × R$ 90 (Opção 2) e o <b>total</b>. Confira antes de pagar.',
       'img': 'img/pt/22-resumo-detalhe.png', 'cap': 'Resumo da cobrança na Opção 2: categorias × R$ 800 + atletas × R$ 90.'},
      {'h': '5. Entenda o parcelamento automático',
       'b': 'O plano é definido pela data do 1º pagamento: <b>até 20/07 → 3x · até 20/08 → 2x · depois → à vista</b>. Vencimentos: 20/07, 20/08 e 20/09/2026. As parcelas aparecem listadas com valor e vencimento, e cada uma tem seu próprio botão <b>Pagar</b>. <b>Atenção:</b> as vagas por categoria são garantidas pela ordem de pagamento da 1ª parcela — quem paga primeiro, garante a vaga.',
       'img': 'img/pt/12-parcelas.png', 'cap': 'As parcelas aparecem listadas com valor, vencimento e botão Pagar.'},
      {'h': '6. Para pagar com Pix',
       'b': 'Selecione <b>PIX</b>, clique em <b>Pagar</b> na parcela desejada e informe o CPF ou CNPJ do pagador (somente números; pedido uma única vez). Aparecem o QR Code e o código “copia e cola”. Pague no app do banco: assim que o Pix cair, <b>a página confirma sozinha</b> — não precisa enviar comprovante. Se o QR expirar, clique em “Novo QR”.',
       'img': 'img/pt/13-pix.png', 'cap': 'Com PIX selecionado, clique em Pagar na parcela desejada.'},
      {'h': '7. Para pagar com cartão',
       'b': 'Selecione <b>Cartão de crédito</b>. As parcelas aparecem listadas como no Pix, cada uma com valor, vencimento e o próprio botão <b>Pagar</b>. Clique em <b>Pagar</b> na parcela desejada: você será redirecionado para o <b>checkout seguro da Stripe</b> e, ao concluir, volta ao portal — a confirmação aparece em instantes. Se preferir, pague algumas parcelas no Pix e outras no cartão.',
       'img': 'img/pt/14-cartao.png', 'cap': 'Selecione Cartão de crédito e pague cada parcela no checkout da Stripe.'},
      {'h': '8. Acompanhe o status do pagamento',
       'b': 'O resumo mostra: <b>Aguardando pagamento → Pagamento em andamento</b> (com contador de parcelas pagas, ex.: 1/3) <b>→ ✓ Confirmado</b>. Lembre: a 1ª parcela garante a vaga; a inscrição é confirmada após a quitação total.',
       'img': 'img/pt/15-resumo-status.png', 'cap': 'O Resumo da cobrança mostra o total e o status do pagamento.'},
    ]},
    {'title': 'PARTE 4 — Cadastrar atletas e enviar a escalação', 'steps': [
      {'h': '1. Adicione cada atleta',
       'b': 'Na aba Atletas, clique em <b>+ Atleta</b> e preencha: nome completo (obrigatório), nº da camisa, categoria, e-mail, data de nascimento e CPF/passaporte. Clique em <b>“Adicionar atleta”</b>.',
       'img': 'img/pt/16-add-atleta.png', 'cap': 'O botão + Atleta fica no topo da aba Atletas.'},
      {'h': '2. Sempre que possível, informe o e-mail do atleta',
       'b': 'Atleta cadastrado com e-mail recebe um <b>convite automático</b> para criar a própria conta no Portal do Atleta e completar o cadastro: foto de rosto, documento (RG/passaporte), histórico esportivo e aceite dos termos (direito de imagem e antidoping). O regulamento exige que o e-mail do atleta esteja na lista do clube.',
       'img': 'img/pt/17-form-atleta.png', 'cap': 'Preencha o formulário e informe o e-mail do atleta sempre que possível.'},
      {'h': '3. Acompanhe o painel por categoria',
       'b': 'Os cartões no topo mostram o total de atletas por categoria com código de cores: <b>verde ✓</b> ok (12–20) · <b>laranja ⚠</b> faltam atletas (mín. 12) · <b>vermelho ✕</b> excede o limite (máx. 20). Clique em um cartão para filtrar a lista por categoria. Categoria sem nenhum atleta é tratada como “não inscrita”. Além dos atletas, são permitidos até <b>7 staff/coaches</b> por categoria.',
       'img': 'img/pt/18-painel-categorias.png', 'cap': 'Os cartões mostram o total por categoria com o código de cores.'},
      {'h': '4. Acompanhe a coluna “Portal” de cada atleta',
       'b': 'Ela mostra o andamento do cadastro individual: <b>Sem conta</b> (não iniciou) → <b>Verificar e-mail</b> (precisa clicar no link do convite) → perfil incompleto → <b>✓ Aprovado / Ativo</b>. Use essa coluna para cobrar os atletas pendentes antes do prazo.',
       'img': 'img/pt/19-coluna-portal.png', 'cap': 'A coluna Portal mostra o andamento do cadastro individual de cada atleta.'},
      {'h': '5. Edite ou remova quando precisar',
       'b': 'Use o botão ✎ para corrigir os dados de um atleta e o ✕ para excluir. Os contadores por categoria recalculam na hora.'},
      {'h': '6. Envie a escalação',
       'b': 'Quando todas as categorias ativas estiverem com 12 a 20 atletas, o botão <b>“Enviar Escalação”</b> é liberado. Se aparecer <b>“Bloqueado”</b>, o aviso mostra exatamente o que falta em cada categoria (ex.: “Feminino: 9/12, faltam 3”). Apenas times aprovados conseguem enviar. <b>Prazo final: 30/09/2026</b>.',
       'img': 'img/pt/20-enviar-bloqueado.png', 'cap': 'Enquanto faltam atletas, o botão aparece como Bloqueado e o aviso detalha o que falta.'},
      {'h': '7. Depois do envio',
       'b': 'Aparece a confirmação <b>“Escalação enviada!”</b> e a organização recebe o roster completo. Precisa alterar algo depois do envio? Fale com a organização pelo e-mail ou WhatsApp do rodapé.'},
    ]},
  ],
  'dates_title': 'DATAS IMPORTANTES',
  'dates': [
    ('20/07', '1ª parcela do pagamento de inscrição'),
    ('20/08', '2ª parcela do pagamento de inscrição'),
    ('20/09', '3ª parcela do pagamento de inscrição'),
    ('30/09', 'Aprovação de documentos dos atletas e prazo do roster completo'),
    ('31/10', 'Cerimônia de abertura e início da fase de grupos'),
  ],
  'checklist_title': 'CHECKLIST FINAL DO TIME',
  'checklist': [
    'Conta criada, e-mail confirmado e cadastro aprovado',
    'Pagamento da taxa de inscrição confirmado (todas as parcelas)',
    'Roster completo enviado (12–20 atletas por categoria)',
    'Documentos de identificação de todos os atletas (RG/passaporte)',
    'Uniformes em conformidade: 2 jogos de camisas numeradas (claro e escuro), calções sem bolsos, cleats de borracha',
  ],
  'final_footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
},
# ══════════════════════════════ ES ══════════════════════════════
'es': {
  'filename': 'Guia-Ilustrada-Inscripcion-Equipos-BFWC2026-ES.pdf',
  'title': 'Guía Ilustrada de Inscripción de Equipos',
  'subtitle': 'Brasil Flag World Championship 2026 · Paso a paso con imágenes, desde la creación de la cuenta hasta el envío de la alineación',
  'footer': 'Guía Ilustrada de Inscripción de Equipos · BFWC 2026 · página {n}',
  'deadlines_title': 'PLAZOS DE INSCRIPCIÓN',
  'deadlines_body': 'Del <b>07/07 al 12/07</b>, la inscripción es exclusiva para equipos ya pre-inscritos — usa el mismo correo informado en la pre-inscripción. A partir del <b>13/07</b>, el registro queda abierto para cualquier equipo.<br/><b>Plazas limitadas:</b> las plazas por categoría se llenan por orden de inscripción y reserva — asegura su lugar quien paga la 1.ª cuota primero. Cuando la categoría se llena, las inscripciones cierran.<br/>¿Dudas? Correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>Cómo usar esta guía:</b> las flechas amarillas en las imágenes muestran exactamente dónde hacer clic en cada paso.',
  'timeline_title': 'RESUMEN — LÍNEA DE TIEMPO DE LA INSCRIPCIÓN',
  'timeline': [
    ('1', 'Registro del club', '07/07 al 12/07 — pre-inscritos · desde el 13/07 — abierto a todos'),
    ('2', 'Elección de las categorías', 'Al crear la cuenta (Etapa 2 del registro)'),
    ('3', 'Pago de la 1.ª cuota — <b>asegura la plaza</b>', 'Hasta el <b>20/07</b> · plazas llenadas por los pagos efectuados primero'),
    ('4', 'Pago de las cuotas restantes', '2.ª hasta el 20/08 · 3.ª hasta el 20/09'),
    ('5', 'Registro de los atletas', 'Hasta el 30/09'),
    ('6', 'Envío de la alineación', 'Hasta el 30/09'),
    ('✓', '<b>¡Inscripción finalizada!</b>', 'Nos vemos en Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Crear la cuenta del club', 'steps': [
      {'h': '1. Accede al sitio y haz clic en “Inscribir Mi Equipo”',
       'b': 'Entra en <b>www.brasilflagworldchampionship.com</b>. En la página principal, haz clic en el botón amarillo <b>Inscribir Mi Equipo</b> (ver flecha) o ve a Portal → Registro de Club. Funciona en el celular y en la computadora.',
       'img': 'img/es/01-home.png', 'cap': 'La flecha indica el botón “Inscribir Mi Equipo” en la página principal.'},
      {'h': '2. Elige el idioma',
       'b': 'En la primera pantalla, selecciona Português, English o <b>Español</b>. Todo el portal seguirá el idioma elegido.',
       'img': 'img/es/02-cadastro-idioma.png', 'cap': 'Haz clic en “Entrar en Español” para continuar en ES.'},
      {'h': '3. Etapa 1 · Completa los datos del club',
       'b': '<b>Este registro se utilizará durante todo el campeonato.</b> Los campos marcados con * son obligatorios: <b>Nombre del club*</b>, <b>País*</b> y Ciudad, <b>Nombre del responsable*</b>, Cargo/Función, <b>Correo electrónico*</b> (se usará en el login y las comunicaciones), WhatsApp (con código de país/área) y el Logo del club (PNG o JPG, máx. 2 MB, opcional).',
       'img': 'img/es/03-etapa1-dados.png', 'cap': 'Formulario de la Etapa 1 — comienza por el Nombre del club.'},
      {'h': '4. Haz clic en “Continuar”',
       'b': '¿Todo listo? Haz clic en el botón azul <b>Continuar</b> al final del formulario.',
       'img': 'img/es/04-continuar.png', 'cap': 'El botón Continuar está justo debajo del campo del logo.'},
      {'h': '5. Etapa 2 · Selecciona las categorías',
       'b': 'Marca las categorías en las que el club planea participar: <b>Masculino, Feminino, Sub-15</b> y/o <b>Sub-12</b> (al menos una).',
       'img': 'img/es/05-categorias.png', 'cap': 'Haz clic en las tarjetas para marcar las categorías deseadas.'},
      {'h': '6. Informa el número estimado de atletas',
       'b': 'Para cada categoría marcada aparece un campo <b>N.º de atletas</b>. Completa la estimación y haz clic en <b>Continuar</b>.',
       'img': 'img/es/06-num-atletas.png', 'cap': 'Con las categorías marcadas, informa el n.º de atletas y haz clic en Continuar.'},
      {'h': '7. Etapa 3 · Crea la contraseña',
       'b': 'Define una contraseña de <b>mínimo 8 caracteres</b> y repítela en el campo de confirmación.',
       'img': 'img/es/07-senha.png', 'cap': 'Campos de contraseña y confirmación en la Etapa 3.'},
      {'h': '8. Acepta los términos y haz clic en “Crear Cuenta”',
       'b': 'Lee los Términos y Condiciones, marca <b>“He leído y acepto los términos y condiciones”</b> (flecha izquierda) y haz clic en <b>Crear Cuenta</b> (flecha derecha).',
       'img': 'img/es/08-termos-criar-conta.png', 'cap': 'Marca la aceptación de los términos y finaliza en Crear Cuenta.'},
      {'h': '9. Confirma el correo',
       'b': 'Recibirás un correo de confirmación. Ábrelo (revisa también el <b>spam</b>) y haz clic en el enlace para <b>activar la cuenta</b>. Sin esta confirmación, el registro no avanza.'},
      {'h': '10. Espera la aprobación de la organización',
       'b': 'Tras la verificación del correo, la organización analiza el registro. Recibirás un correo de aprobación — <b>solo entonces se habilita el pago</b> en el portal.'},
    ]},
    {'title': 'PARTE 2 — Entrar al portal del equipo', 'steps': [
      {'h': '1. Accede al Área de Equipos y elige el idioma',
       'b': 'Accede a <b>/portal/times/login</b>. La primera pantalla pide el idioma — haz clic en <b>Entrar en Español</b>.',
       'img': 'img/es/09-login-idioma.png', 'cap': 'Pantalla de idioma del Área de Equipos.'},
      {'h': '2. Inicia sesión',
       'b': 'Ingresa con el <b>correo del responsable</b> (el mismo del registro) y la contraseña, y haz clic en <b>Entrar al Área del Equipo</b>. Importante: el acceso solo se habilita después de confirmar el correo y de que la organización apruebe el registro. ¿Olvidaste la contraseña? Haz clic en <b>“Olvidé mi contraseña”</b>, justo encima del botón.',
       'img': 'img/es/10-login.png', 'cap': 'La flecha indica el botón de acceso. El enlace “Olvidé mi contraseña” está justo arriba.'},
      {'h': '3. Si aparece un mensaje de error, esto es lo que significa',
       'b': '<b>“Correo no verificado”</b>: abre el correo de confirmación y haz clic en el enlace (revisa el spam). · <b>“Registro en espera de aprobación”</b>: la organización aún está analizando; espera el correo de aprobación. · <b>“Contraseña incorrecta”</b>: verifica la contraseña. · <b>“No se encontró ninguna cuenta”</b>: verifica el correo — debe ser exactamente el usado en el registro. · El enlace de restablecimiento vale por 1 hora.'},
      {'h': '4. Conoce la pantalla inicial',
       'b': 'El portal abre en la pestaña <b>Información</b>, en el idioma elegido en el registro. Arriba están el nombre y el logo del club y el botón <b>Salir</b>. En el celular, las pestañas aparecen en la parte inferior de la pantalla.'},
      {'h': '5. Pestaña Información · Valores, plazos y cupos',
       'b': 'Reúne todo lo que el equipo necesita saber antes de pagar: ventanas de confirmación (07/07 al 12/07 prioridad para pre-inscritos; 13/07 al 20/07 abierto a cualquier equipo), las dos opciones de valores, las cuotas, el equipamiento exigido y hospedaje/logística. <b>Atención: los cupos por categoría son limitados</b> y se llenan por orden de pago de la 1.ª cuota — cuando la categoría se llena, las inscripciones cierran.'},
      {'h': '6. Pestaña Inscripción · Sigue tu situación',
       'b': 'Muestra una línea de tiempo con las 5 etapas de la inscripción — <b>Pre-inscripción → Pago → Inscripción confirmada → Registro de atletas → Aprobado</b> — con sellos de “completado” y “en curso”, además de los datos del registro, las fechas importantes y un checklist de documentos para organizar al equipo.'},
      {'h': '7. Pestaña Pago · Paga la inscripción',
       'b': 'Es donde eliges la modalidad de inscripción, sigues las cuotas y pagas con <b>tarjeta de crédito</b> (o transferencia Wise). Se habilita tras la aprobación — el paso a paso completo está en la <b>Parte 3</b>.'},
      {'h': '8. Pestaña Atletas · Arma el roster',
       'b': 'Registro de atletas, seguimiento por categoría y envío de la alineación — detallado en la <b>Parte 4</b>.'},
      {'h': '9. Pestaña Campeonato · Partidos y resultados',
       'b': 'Tabla de próximos partidos, resultados, estadísticas y anotadores de tu equipo, ranking general y mapa de la sede en Leme, SP. Los horarios se publican tras el cierre de las inscripciones.'},
    ]},
    {'title': 'PARTE 3 — Pagar la inscripción', 'steps': [
      {'h': '1. Abre la pestaña Pago',
       'b': 'Se habilita después de que el registro es aprobado. Mientras tanto, la pestaña Inscripción muestra <b>“Esperando la aprobación de la organización para habilitar el pago”</b>.'},
      {'h': '2. Elige la modalidad de inscripción',
       'b': '<b>Opción 1 · Paquete:</b> R$ 2.000 por categoría, con atletas incluidos. · <b>Opción 2 · Por atleta:</b> R$ 800 por categoría + R$ 90 por atleta. Puedes cambiar de opción libremente (botón <b>“Cambiar opción”</b>) hasta el primer pago — después queda bloqueada.',
       'img': 'img/es/11-pagamento-opcao.png', 'cap': 'Elige entre Opción 1 · Paquete y Opción 2 · Por atleta.'},
      {'h': '3. En la Opción 2, ajusta la cantidad de atletas',
       'b': 'Aparece un contador por categoría (botones + y −, R$ 90 por atleta). El total se recalcula al instante. Esta cantidad también queda bloqueada tras el primer pago.',
       'img': 'img/es/21-opcao2-contador.png', 'cap': 'En la Opción 2, ajusta la cantidad de atletas por categoría con los botones + y −.'},
      {'h': '4. Revisa el “Resumen del cobro”',
       'b': 'La tarjeta al final de la pestaña muestra el detalle: categorías × valor de la opción, atletas × R$ 90 (Opción 2) y el <b>total</b>. Revísalo antes de pagar.',
       'img': 'img/es/22-resumo-detalhe.png', 'cap': 'Resumen del cobro en la Opción 2: categorías × R$ 800 + atletas × R$ 90.'},
      {'h': '5. Entiende las cuotas automáticas',
       'b': 'El plan se define por la fecha del 1.er pago: <b>hasta el 20/07 → 3 cuotas · hasta el 20/08 → 2 cuotas · después → pago único</b>. Vencimientos: 20/07, 20/08 y 20/09/2026. Las cuotas aparecen listadas con valor y vencimiento, cada una con su propio botón <b>Pagar</b>. <b>Atención:</b> las plazas por categoría se garantizan por orden de pago de la 1.ª cuota — quien paga primero, asegura su lugar.',
       'img': 'img/es/12-parcelas.png', 'cap': 'Las cuotas aparecen listadas con monto, vencimiento y botón Pagar.'},
      {'h': '6. Para pagar con tarjeta',
       'b': 'Selecciona <b>Tarjeta de crédito</b>. Las cuotas aparecen listadas con monto, vencimiento y su propio botón <b>Pagar</b>. Haz clic en <b>Pagar</b> en la cuota deseada: serás redirigido al <b>checkout seguro de Stripe</b> y, al terminar, vuelves al portal — la confirmación aparece en instantes. Se aceptan tarjetas internacionales; el cobro es en reales (BRL) y tu banco hace la conversión a tu moneda.',
       'img': 'img/es/14-cartao.png', 'cap': 'Selecciona Tarjeta de crédito y paga cada cuota en el checkout de Stripe.'},
      {'h': '7. Para pagar por transferencia (Wise)',
       'b': '¿Prefieres una transferencia internacional? La organización acepta <b>Wise</b>. Contacta a <b>Leonardo</b> — correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 81 99565-8710</b> — para coordinar la transferencia y confirmar tus cuotas en el portal.'},
      {'h': '8. Sigue el estado del pago',
       'b': 'El resumen muestra: <b>Esperando pago → Pago en curso</b> (con contador de cuotas pagadas, ej.: 1/3) <b>→ ✓ Confirmado</b>. Recuerda: la 1.ª cuota asegura el cupo; la inscripción se confirma tras el pago total.',
       'img': 'img/es/15-resumo-status.png', 'cap': 'El Resumen del cobro muestra el total y el estado del pago.'},
    ]},
    {'title': 'PARTE 4 — Registrar atletas y enviar la alineación', 'steps': [
      {'h': '1. Agrega a cada atleta',
       'b': 'En la pestaña Atletas, haz clic en <b>+ Atleta</b> y completa: nombre completo (obligatorio), n.º de camiseta, categoría, correo, fecha de nacimiento y CPF/pasaporte. Haz clic en <b>“Agregar atleta”</b>.',
       'img': 'img/es/16-add-atleta.png', 'cap': 'El botón + Atleta está en la parte superior de la pestaña Atletas.'},
      {'h': '2. Siempre que sea posible, informa el correo del atleta',
       'b': 'El atleta registrado con correo recibe una <b>invitación automática</b> para crear su propia cuenta en el Portal del Atleta y completar su perfil: foto del rostro, documento (RG/pasaporte), historial deportivo y aceptación de los términos (derechos de imagen y antidopaje). El reglamento exige que el correo del atleta esté en la lista del club.',
       'img': 'img/es/17-form-atleta.png', 'cap': 'Completa el formulario e informa el correo del atleta siempre que sea posible.'},
      {'h': '3. Sigue el panel por categoría',
       'b': 'Las tarjetas de arriba muestran el total de atletas por categoría con código de colores: <b>verde ✓</b> ok (12–20) · <b>naranja ⚠</b> faltan atletas (mín. 12) · <b>rojo ✕</b> excede el límite (máx. 20). Haz clic en una tarjeta para filtrar la lista por categoría. Una categoría sin atletas se trata como “no inscrita”. Además de los atletas, se permiten hasta <b>7 staff/coaches</b> por categoría.',
       'img': 'img/es/18-painel-categorias.png', 'cap': 'Las tarjetas muestran el total por categoría con el código de colores.'},
      {'h': '4. Observa la columna “Portal” de cada atleta',
       'b': 'Muestra el avance del registro individual: <b>Sin cuenta</b> (no inició) → <b>Verificar correo</b> (debe hacer clic en el enlace de la invitación) → perfil incompleto → <b>✓ Aprobado / Activo</b>. Usa esta columna para reclamar a los atletas pendientes antes del plazo.',
       'img': 'img/es/19-coluna-portal.png', 'cap': 'La columna Portal muestra el avance del registro individual de cada atleta.'},
      {'h': '5. Edita o elimina cuando haga falta',
       'b': 'Usa el botón ✎ para corregir los datos de un atleta y ✕ para eliminar. Los contadores por categoría se recalculan al instante.'},
      {'h': '6. Envía la alineación',
       'b': 'Cuando todas las categorías activas tengan de 12 a 20 atletas, se habilita el botón <b>“Enviar Alineación”</b>. Si aparece <b>“Bloqueado”</b>, el aviso muestra exactamente qué falta en cada categoría (ej.: “Feminino: 9/12, faltan 3”). Solo los equipos aprobados pueden enviar. <b>Plazo final: 30/09/2026</b>.',
       'img': 'img/es/20-enviar-bloqueado.png', 'cap': 'Mientras falten atletas, el botón aparece como Bloqueado y el aviso detalla qué falta.'},
      {'h': '7. Después del envío',
       'b': 'Aparece la confirmación <b>“¡Alineación enviada!”</b> y la organización recibe el roster completo. ¿Necesitas cambiar algo después del envío? Contacta a la organización por el correo o WhatsApp del pie de página.'},
    ]},
  ],
  'dates_title': 'FECHAS IMPORTANTES',
  'dates': [
    ('20/07', '1.ª cuota del pago de inscripción'),
    ('20/08', '2.ª cuota del pago de inscripción'),
    ('20/09', '3.ª cuota del pago de inscripción'),
    ('30/09', 'Aprobación de documentos de los atletas y plazo del roster completo'),
    ('31/10', 'Ceremonia de apertura e inicio de la fase de grupos'),
  ],
  'checklist_title': 'CHECKLIST FINAL DEL EQUIPO',
  'checklist': [
    'Cuenta creada, correo confirmado y registro aprobado',
    'Pago de la tasa de inscripción confirmado (todas las cuotas)',
    'Roster completo enviado (12–20 atletas por categoría)',
    'Documentos de identificación de todos los atletas (RG/pasaporte)',
    'Uniformes conformes: 2 juegos de camisetas numeradas (clara y oscura), shorts sin bolsillos, tacos de goma',
  ],
  'final_footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
},
# ══════════════════════════════ EN ══════════════════════════════
'en': {
  'filename': 'Illustrated-Team-Registration-Guide-BFWC2026-EN.pdf',
  'title': 'Illustrated Team Registration Guide',
  'subtitle': 'Brasil Flag World Championship 2026 · Step by step with images, from account creation to lineup submission',
  'footer': 'Illustrated Team Registration Guide · BFWC 2026 · page {n}',
  'deadlines_title': 'REGISTRATION DEADLINES',
  'deadlines_body': 'From <b>Jul 7 to Jul 12</b>, registration is exclusive to pre-registered teams — use the same email provided in your pre-registration. From <b>Jul 13</b>, registration is open to any team.<br/><b>Limited spots:</b> spots per category are filled in order of registration and reservation — the spot goes to whoever pays the 1st installment first. Once a category is full, registration closes.<br/>Questions? Email <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>How to use this guide:</b> the yellow arrows in the images show exactly where to click at each step.',
  'timeline_title': 'SUMMARY — REGISTRATION TIMELINE',
  'timeline': [
    ('1', 'Club registration', 'Jul 7–12 — pre-registered · from Jul 13 — open to all'),
    ('2', 'Category selection', 'During account creation (Step 2)'),
    ('3', '1st installment payment — <b>secures your spot</b>', 'By <b>Jul 20</b> · spots filled by earliest payments first'),
    ('4', 'Remaining installments', '2nd by Aug 20 · 3rd by Sep 20'),
    ('5', 'Athlete registration', 'By Sep 30'),
    ('6', 'Lineup submission', 'By Sep 30'),
    ('✓', '<b>Registration complete!</b>', 'See you in Leme, SP — Oct 31'),
  ],
  'parts': [
    {'title': 'PART 1 — Create your club account', 'steps': [
      {'h': '1. Go to the website and click “Register My Team”',
       'b': 'Visit <b>www.brasilflagworldchampionship.com</b>. On the home page, click the yellow <b>Register My Team</b> button (see arrow) or go to Portal → Club Registration. Works on mobile and desktop.',
       'img': 'img/en/01-home.png', 'cap': 'The arrow points to the “Register My Team” button on the home page.'},
      {'h': '2. Choose your language',
       'b': 'On the first screen, select Português, <b>English</b> or Español. The entire portal will follow the chosen language.',
       'img': 'img/en/02-cadastro-idioma.png', 'cap': 'Click “Enter in English” to continue in English.'},
      {'h': '3. Step 1 · Fill in your club details',
       'b': '<b>This registration will be used throughout the entire championship.</b> Fields marked with * are required: <b>Club name*</b>, <b>Country*</b> and City, <b>Contact name*</b>, Role/Position, <b>Email*</b> (used for login and communications), WhatsApp (with country/area code) and the Club logo (PNG or JPG, max 2 MB, optional).',
       'img': 'img/en/03-etapa1-dados.png', 'cap': 'Step 1 form — start with the Club name.'},
      {'h': '4. Click “Continue”',
       'b': 'All set? Click the blue <b>Continue</b> button at the bottom of the form.',
       'img': 'img/en/04-continuar.png', 'cap': 'The Continue button sits right below the logo field.'},
      {'h': '5. Step 2 · Select your categories',
       'b': "Check the categories your club plans to enter: <b>Men's (Masculino), Women's (Feminino), U-15 (Sub-15)</b> and/or <b>U-12 (Sub-12)</b> (at least one).",
       'img': 'img/en/05-categorias.png', 'cap': 'Click the cards to select your categories.'},
      {'h': '6. Enter the estimated number of athletes',
       'b': 'For each selected category, a <b>No. of athletes</b> field appears. Fill in your estimate and click <b>Continue</b>.',
       'img': 'img/en/06-num-atletas.png', 'cap': 'With categories selected, enter the athlete count and click Continue.'},
      {'h': '7. Step 3 · Create your password',
       'b': 'Set a password of <b>at least 8 characters</b> and repeat it in the confirmation field.',
       'img': 'img/en/07-senha.png', 'cap': 'Password and confirmation fields in Step 3.'},
      {'h': '8. Accept the terms and click “Create Account”',
       'b': 'Read the Terms and Conditions, check <b>“I have read and accept the terms and conditions”</b> (left arrow) and click <b>Create Account</b> (right arrow).',
       'img': 'img/en/08-termos-criar-conta.png', 'cap': 'Check the terms box and finish with Create Account.'},
      {'h': '9. Confirm your email',
       'b': 'You will receive a confirmation email. Open it (also check your <b>spam</b> folder) and click the link to <b>activate your account</b>. Without this confirmation, registration does not move forward.'},
      {'h': "10. Wait for the organization's approval",
       'b': 'After email verification, the organization reviews your registration. You will receive an approval email — <b>only then is payment unlocked</b> in the portal.'},
    ]},
    {'title': 'PART 2 — Enter the team portal', 'steps': [
      {'h': '1. Go to the Team Area and choose your language',
       'b': 'Go to <b>/portal/times/login</b>. The first screen asks for the language — click <b>Enter in English</b>.',
       'img': 'img/en/09-login-idioma.png', 'cap': 'Team Area language screen.'},
      {'h': '2. Log in',
       'b': 'Enter the <b>contact email</b> (the same used at registration) and your password, then click <b>Enter Team Area</b>. Important: login is only unlocked after the email is confirmed and the registration approved by the organization. Forgot your password? Click <b>“Forgot my password”</b> just above the button.',
       'img': 'img/en/10-login.png', 'cap': 'The arrow points to the login button. The “Forgot my password” link is right above it.'},
      {'h': '3. If you see an error message, here is what it means',
       'b': '<b>“Email not verified”</b>: open the confirmation email and click the link (check spam). · <b>“Registration awaiting approval”</b>: the organization is still reviewing; wait for the approval email. · <b>“Incorrect password”</b>: check the typed password. · <b>“No account found”</b>: check the email — it must be exactly the one used at registration. · The password reset link is valid for 1 hour.'},
      {'h': '4. Get to know the home screen',
       'b': 'The portal opens on the <b>Information</b> tab, in the language chosen at registration. At the top are the club name and logo and the <b>Sign out</b> button. On mobile, the tabs appear at the bottom of the screen.'},
      {'h': '5. Information tab · Fees, deadlines and spots',
       'b': 'Everything your team needs to know before paying: confirmation windows (Jul 7–12 priority for pre-registered; Jul 13–20 open to any team), the two pricing options, installments, required equipment and lodging/logistics. <b>Attention: spots per category are limited</b> and filled by order of first-installment payment — once a category is full, registration closes.'},
      {'h': '6. Registration tab · Track your status',
       'b': 'Shows a timeline with the 5 registration stages — <b>Pre-registration → Payment → Registration confirmed → Athlete registration → Approved</b> — with “done” and “in progress” badges, plus your registration data, key dates and a document checklist to keep your team organized.'},
      {'h': '7. Payment tab · Pay the registration fee',
       'b': 'Where you choose the registration option, track installments and pay by <b>credit card</b> (or Wise transfer). Unlocked after approval — the full walkthrough is in <b>Part 3</b>.'},
      {'h': '8. Athletes tab · Build the roster',
       'b': 'Athlete registration, per-category tracking and lineup submission — detailed in <b>Part 4</b>.'},
      {'h': '9. Championship tab · Games and results',
       'b': 'Upcoming games, results, statistics and top scorers for your team, overall ranking and the venue map in Leme, SP. Game schedules are published after registration closes.'},
    ]},
    {'title': 'PART 3 — Pay the registration fee', 'steps': [
      {'h': '1. Open the Payment tab',
       'b': 'It is unlocked once your registration is approved. Until then, the Registration tab shows <b>“Awaiting the organization\'s approval to unlock payment”</b>.'},
      {'h': '2. Choose your registration option',
       'b': '<b>Option 1 · Package:</b> R$ 2,000 per category, athletes included. · <b>Option 2 · Per athlete:</b> R$ 800 per category + R$ 90 per athlete. You can switch freely (<b>“Change option”</b> button) until the first payment — after that it is locked.',
       'img': 'img/en/11-pagamento-opcao.png', 'cap': 'Choose between Option 1 · Package and Option 2 · Per athlete.'},
      {'h': '3. On Option 2, adjust the athlete count',
       'b': 'A per-category counter appears (+ and − buttons, R$ 90 per athlete). The total recalculates instantly. This quantity is also locked after the first payment.',
       'img': 'img/en/21-opcao2-contador.png', 'cap': 'On Option 2, adjust the athlete count per category with the + and − buttons.'},
      {'h': '4. Review the “Billing summary”',
       'b': 'The card at the bottom of the tab shows the breakdown: categories × option price, athletes × R$ 90 (Option 2) and the <b>total</b>. Review before paying.',
       'img': 'img/en/22-resumo-detalhe.png', 'cap': 'Charge summary on Option 2: categories × R$ 800 + athletes × R$ 90.'},
      {'h': '5. Understand the automatic installment plan',
       'b': 'The plan is set by the date of the 1st payment: <b>by Jul 20 → 3x · by Aug 20 → 2x · later → single payment</b>. Due dates: Jul 20, Aug 20 and Sep 20, 2026. Installments are listed with amount and due date, each with its own <b>Pay</b> button. <b>Attention:</b> spots per category are secured in order of payment of the 1st installment — pay first, secure your spot.',
       'img': 'img/en/12-parcelas.png', 'cap': 'Installments are listed with amount, due date and a Pay button.'},
      {'h': '6. Paying with card',
       'b': 'Select <b>Credit card</b>. Installments are listed with amount, due date and their own <b>Pay</b> button. Click <b>Pay</b> on the desired installment: you are redirected to the <b>secure Stripe checkout</b> and, once done, you return to the portal — confirmation appears within moments. International cards are accepted; charges are in Brazilian reais (BRL) and your bank converts to your currency.',
       'img': 'img/en/14-cartao.png', 'cap': 'Select Credit card and pay each installment via the Stripe checkout.'},
      {'h': '7. Paying by bank transfer (Wise)',
       'b': 'Prefer an international bank transfer? The organization accepts <b>Wise</b>. Contact <b>Leonardo</b> — email <b>contato@brasilflag.com</b> · WhatsApp <b>+55 81 99565-8710</b> — to arrange the transfer and have your installments confirmed in the portal.'},
      {'h': '8. Track the payment status',
       'b': 'The summary shows: <b>Awaiting payment → Payment in progress</b> (with paid-installments counter, e.g. 1/3) <b>→ ✓ Confirmed</b>. Remember: the 1st installment secures your spot; registration is confirmed after full payment.',
       'img': 'img/en/15-resumo-status.png', 'cap': 'The Charge summary shows the total and the payment status.'},
    ]},
    {'title': 'PART 4 — Register athletes and submit the lineup', 'steps': [
      {'h': '1. Add each athlete',
       'b': 'On the Athletes tab, click <b>+ Athlete</b> and fill in: full name (required), jersey number, category, email, date of birth and CPF/passport. Click <b>“Add athlete”</b>.',
       'img': 'img/en/16-add-atleta.png', 'cap': 'The + Athlete button sits at the top of the Athletes tab.'},
      {'h': "2. Whenever possible, provide the athlete's email",
       'b': 'An athlete registered with an email automatically receives an <b>invitation</b> to create their own account in the Athlete Portal and complete their profile: face photo, ID document (RG/passport), sports history and acceptance of the terms (image rights and anti-doping). The regulations require the athlete\'s email to be on the club\'s list.',
       'img': 'img/en/17-form-atleta.png', 'cap': "Fill in the form and provide the athlete's email whenever possible."},
      {'h': '3. Track the per-category dashboard',
       'b': 'The cards at the top show total athletes per category with color coding: <b>green ✓</b> ok (12–20) · <b>orange ⚠</b> athletes missing (min. 12) · <b>red ✕</b> over the limit (max. 20). Click a card to filter the list by category. A category with no athletes is treated as “not entered”. Besides athletes, up to <b>7 staff/coaches</b> per category are allowed.',
       'img': 'img/en/18-painel-categorias.png', 'cap': 'The cards show totals per category with the color code.'},
      {'h': "4. Watch each athlete's “Portal” column",
       'b': 'It shows individual registration progress: <b>No account</b> (not started) → <b>Verify email</b> (needs to click the invite link) → incomplete profile → <b>✓ Approved / Active</b>. Use this column to chase pending athletes before the deadline.',
       'img': 'img/en/19-coluna-portal.png', 'cap': "The Portal column shows each athlete's individual registration progress."},
      {'h': '5. Edit or remove whenever needed',
       'b': "Use the ✎ button to fix an athlete's data and ✕ to delete. Per-category counters recalculate instantly."},
      {'h': '6. Submit the lineup',
       'b': 'When every active category has 12 to 20 athletes, the <b>“Submit Lineup”</b> button unlocks. If it shows <b>“Blocked”</b>, the notice details exactly what is missing per category (e.g. “Women\'s: 9/12, 3 missing”). Only approved teams can submit. <b>Final deadline: Sep 30, 2026</b>.',
       'img': 'img/en/20-enviar-bloqueado.png', 'cap': 'While athletes are missing, the button shows Blocked and the notice details what is missing.'},
      {'h': '7. After submission',
       'b': 'The <b>“Lineup submitted!”</b> confirmation appears and the organization receives the full roster. Need changes after submitting? Contact the organization via the email or WhatsApp in the footer.'},
    ]},
  ],
  'dates_title': 'KEY DATES',
  'dates': [
    ('Jul 20', '1st registration payment installment'),
    ('Aug 20', '2nd registration payment installment'),
    ('Sep 20', '3rd registration payment installment'),
    ('Sep 30', 'Athlete document approval and full roster deadline'),
    ('Oct 31', 'Opening ceremony and start of the group stage'),
  ],
  'checklist_title': 'TEAM FINAL CHECKLIST',
  'checklist': [
    'Account created, email confirmed and registration approved',
    'Registration fee payment confirmed (all installments)',
    'Full roster submitted (12\u201320 athletes per category)',
    'ID documents for all athletes (RG/passport)',
    'Compliant uniforms: 2 sets of numbered jerseys (light and dark), pocketless shorts, rubber cleats',
  ],
  'final_footer': 'Brasil Flag World Championship 2026 \u00b7 Leme, SP \u00b7 www.brasilflagworldchampionship.com \u00b7 contato@brasilflag.com',
},
}
