# -*- coding: utf-8 -*-
"""Conteúdo do guia ILUSTRADO dos ATLETAS (PT) — BFWC 2026.
Cada passo: h=título, b=corpo (<b>), img=screenshot (opcional), cap=legenda (opcional)."""

ILU = {
'pt': {
  'filename': 'Guia-Ilustrado-Inscricao-Atletas-BFWC2026-PT.pdf',
  'title': 'Guia Ilustrado de Inscrição dos Atletas',
  'subtitle': 'Brasil Flag World Championship 2026 · Passo a passo com imagens, do convite do time à inscrição confirmada',
  'footer': 'Guia Ilustrado de Inscrição dos Atletas · BFWC 2026 · página {n}',
  'deadlines_title': 'COMO FUNCIONA A INSCRIÇÃO DO ATLETA',
  'deadlines_body': 'A sua inscrição começa pelo <b>seu time</b>: o clube adiciona você ao roster e você recebe um <b>e-mail de convite</b>. Você cria sua conta com o <b>mesmo e-mail</b>, confirma o e-mail, entra na Área dos Atletas e <b>completa o perfil</b> — foto, documento oficial com foto e, se for <b>menor de 18</b>, a autorização do responsável.<br/>A inscrição dos atletas abre em <b>07/07 às 10h</b> (Brasília). Funciona no celular e no computador.<br/>Dúvidas? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>Como usar este guia:</b> as setas amarelas nas imagens mostram exatamente onde clicar em cada passo.',
  'timeline_title': 'RESUMO — SUA JORNADA COMO ATLETA',
  'timeline': [
    ('1', 'Convite do time', 'Seu clube adiciona você ao roster e você recebe um e-mail'),
    ('2', 'Criar sua conta', 'Com o <b>mesmo e-mail</b> do convite (a partir de 07/07, 10h)'),
    ('3', 'Confirmar o e-mail', 'Clique no link enviado para ativar a conta'),
    ('4', 'Entrar na Área dos Atletas', 'Login com e-mail e senha'),
    ('5', 'Completar o perfil e enviar documentos', 'Foto, documento com foto e (se menor) autorização do responsável'),
    ('✓', '<b>Inscrição confirmada!</b>', 'Nos vemos em Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Receber o convite e criar a conta', 'steps': [
      {'h': '1. Seu time convida você',
       'b': 'A inscrição do atleta parte do <b>seu clube</b>: o técnico/responsável adiciona você ao roster de uma categoria (Masculino, Feminino, Sub-15 ou Sub-12). Você recebe um <b>e-mail de convite</b> do BFWC 2026. Guarde o e-mail — vai usar o mesmo endereço no cadastro.'},
      {'h': '2. Abra o cadastro e escolha o idioma',
       'b': 'Acesse <b>/portal/atletas/cadastro</b>. Na primeira tela, selecione o idioma.',
       'img': 'img/pt-atletas/01-idioma.png', 'cap': 'Clique em “Entrar em Português”.'},
      {'h': '3. Etapa 1 · Preencha seus dados',
       'b': 'Use o <b>mesmo e-mail do convite</b> (o aviso amarelo reforça isso). Preencha nome, e-mail, data de nascimento, nacionalidade, WhatsApp, Instagram e posição. Depois clique em <b>Continuar</b>.',
       'img': 'img/pt-atletas/02-cadastro.png', 'cap': 'Use o mesmo e-mail cadastrado pelo seu clube.'},
      {'h': '4. Crie a senha, aceite os termos e confirme o e-mail',
       'b': 'Nas etapas seguintes, defina uma senha (<b>mín. 8 caracteres</b>), aceite os termos e clique em <b>Criar conta</b>. Depois abra o <b>e-mail de confirmação</b> (veja também o spam) e clique no link para <b>ativar a conta</b>.'},
    ]},
    {'title': 'PARTE 2 — Entrar e completar o perfil', 'steps': [
      {'h': '5. Entre na Área dos Atletas',
       'b': 'Acesse <b>/portal/atletas/login</b>, escolha o idioma e entre com o <b>seu e-mail</b> (o mesmo do convite) e a senha.',
       'img': 'img/pt-atletas/03-login.png', 'cap': 'Área dos Atletas — escolha o idioma para entrar.'},
      {'h': '6. Envie a foto e o documento com foto',
       'b': 'Na aba <b>Meu Perfil</b>, envie uma <b>foto com o rosto visível</b> e anexe um <b>documento oficial com foto</b> (RG, CNH ou passaporte). <b>É o mesmo documento que você levará no dia dos jogos.</b>',
       'img': 'img/pt-atletas/04-foto-documento.png', 'cap': 'Clique para adicionar a foto e para anexar o documento.'},
      {'h': '7. Aceite os termos e salve',
       'b': 'Preencha os dados pessoais, contato de emergência e dados esportivos, marque os <b>5 termos obrigatórios</b> e clique em <b>Salvar progresso</b>. Com tudo completo, sua <b>inscrição fica confirmada</b>.',
       'img': 'img/pt-atletas/05-termos.png', 'cap': 'Aceite os 5 termos e clique em “Salvar progresso”.'},
      {'h': '8. Menor de 18? Autorização do responsável',
       'b': 'Se na data do evento você tiver <b>menos de 18 anos</b> (Sub-15 e Sub-12), é obrigatório enviar a <b>autorização do responsável</b>. <b>Baixe o modelo (PDF)</b>, peça para o responsável legal preencher e assinar, e <b>anexe</b> o arquivo. Prazo: <b>30/09</b>.',
       'img': 'img/pt-atletas/06-autorizacao.png', 'cap': 'Baixe o modelo, colha a assinatura e anexe a autorização.'},
    ]},
    {'title': 'PARTE 3 — No dia do jogo', 'steps': [
      {'h': '9. Leve o mesmo documento',
       'b': 'No dia dos jogos, leve o <b>mesmo documento oficial com foto</b> que você anexou no portal — ele será usado para validar sua identidade no credenciamento. Dúvidas? Fale com o responsável do seu time ou com a organização (<b>contato@brasilflag.com</b>).'},
    ]},
  ],
  'dates_title': 'DATAS IMPORTANTES',
  'dates': [
    ('07/07', 'Abertura da inscrição dos atletas (10h, horário de Brasília)'),
    ('30/09', 'Prazo final da inscrição de atletas e da aprovação de documentos'),
    ('31/10 a 02/11', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'CHECKLIST DO ATLETA',
  'checklist': [
    'Recebi o convite do meu time e usei o MESMO e-mail no cadastro',
    'Criei minha conta e confirmei o e-mail (cliquei no link)',
    'Entrei na Área dos Atletas com e-mail e senha',
    'Enviei uma foto com o rosto visível',
    'Anexei meu documento oficial com foto (RG, CNH ou passaporte)',
    'Sou menor de 18: enviei a autorização do responsável assinada',
    'Vou levar o mesmo documento no dia dos jogos',
  ],
  'final_footer': 'Seja bem-vindo ao Brasil Flag World Championship 2026. Nos vemos em Leme, SP!',
},

'en': {
  'filename': 'Illustrated-Athlete-Registration-Guide-BFWC2026-EN.pdf',
  'title': 'Illustrated Athlete Registration Guide',
  'subtitle': 'Brasil Flag World Championship 2026 · Step by step with images, from your team invite to a confirmed registration',
  'footer': 'Illustrated Athlete Registration Guide · BFWC 2026 · page {n}',
  'deadlines_title': 'HOW ATHLETE REGISTRATION WORKS',
  'deadlines_body': 'Your registration starts with <b>your team</b>: the club adds you to the roster and you receive an <b>invitation e-mail</b>. You create your account using <b>the same e-mail</b>, verify it, log in to the Athletes Area and <b>complete your profile</b> — photo, official photo ID and, if <b>under 18</b>, the guardian authorization.<br/>Athlete registration opens on <b>July 7 at 10 AM</b> (Brasília). Works on phone and computer.<br/>Questions? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>How to use this guide:</b> the yellow arrows in the images show exactly where to click at each step. (Screens shown in Portuguese; the layout is identical in English.)',
  'timeline_title': 'SUMMARY — YOUR JOURNEY AS AN ATHLETE',
  'timeline': [
    ('1', 'Team invite', 'Your club adds you to the roster and you get an e-mail'),
    ('2', 'Create your account', 'With the <b>same e-mail</b> from the invite (from July 7, 10 AM)'),
    ('3', 'Verify your e-mail', 'Click the link sent to activate the account'),
    ('4', 'Log in to the Athletes Area', 'Log in with e-mail and password'),
    ('5', 'Complete your profile and upload documents', 'Photo, photo ID and (if a minor) guardian authorization'),
    ('✓', '<b>Registration confirmed!</b>', 'See you in Leme, SP — Oct 31'),
  ],
  'parts': [
    {'title': 'PART 1 — Get the invite and create your account', 'steps': [
      {'h': '1. Your team invites you',
       'b': 'Athlete registration starts from <b>your club</b>: the coach/manager adds you to a category roster (Men, Women, U-15 or U-12). You get an <b>invitation e-mail</b> from BFWC 2026. Keep that e-mail — you will use the same address to register.'},
      {'h': '2. Open registration and choose the language',
       'b': 'Go to <b>/portal/atletas/cadastro</b>. On the first screen, select the language.',
       'img': 'img/pt-atletas/01-idioma.png', 'cap': 'Click your language to continue (here: Português).'},
      {'h': '3. Step 1 · Fill in your details',
       'b': 'Use the <b>same e-mail from the invite</b> (the yellow warning reminds you). Fill in name, e-mail, date of birth, nationality, WhatsApp, Instagram and position, then click <b>Continue</b>.',
       'img': 'img/pt-atletas/02-cadastro.png', 'cap': 'Use the same e-mail registered by your club.'},
      {'h': '4. Create a password, accept the terms and verify your e-mail',
       'b': 'On the next steps, set a password (<b>min. 8 characters</b>), accept the terms and click <b>Create account</b>. Then open the <b>confirmation e-mail</b> (check spam) and click the link to <b>activate the account</b>.'},
    ]},
    {'title': 'PART 2 — Log in and complete your profile', 'steps': [
      {'h': '5. Log in to the Athletes Area',
       'b': 'Go to <b>/portal/atletas/login</b>, choose the language and sign in with <b>your e-mail</b> (the same from the invite) and your password.',
       'img': 'img/pt-atletas/03-login.png', 'cap': 'Athletes Area — choose the language to log in.'},
      {'h': '6. Upload your photo and photo ID',
       'b': 'On the <b>Profile</b> tab, upload a <b>photo with your face visible</b> and attach an <b>official photo ID</b> (national ID, driver license or passport). <b>It is the same document you must bring on game day.</b>',
       'img': 'img/pt-atletas/04-foto-documento.png', 'cap': 'Click to add the photo and to attach the document.'},
      {'h': '7. Accept the terms and save',
       'b': 'Fill in personal details, emergency contact and sports data, check the <b>5 required terms</b> and click <b>Save progress</b>. Once complete, your <b>registration is confirmed</b>.',
       'img': 'img/pt-atletas/05-termos.png', 'cap': 'Accept the 5 terms and click "Save progress".'},
      {'h': '8. Under 18? Guardian authorization',
       'b': 'If you are <b>under 18</b> on the event date (U-15 and U-12), you must upload the <b>guardian authorization</b>. <b>Download the template (PDF)</b>, have your legal guardian fill it and sign, and <b>attach</b> the file. Deadline: <b>Sep 30</b>.',
       'img': 'img/pt-atletas/06-autorizacao.png', 'cap': 'Download the template, get it signed and attach the authorization.'},
    ]},
    {'title': 'PART 3 — Game day', 'steps': [
      {'h': '9. Bring the same document',
       'b': 'On game day, bring the <b>same official photo ID</b> you uploaded — it will verify your identity at accreditation. Questions? Talk to your team manager or the organization (<b>contato@brasilflag.com</b>).'},
    ]},
  ],
  'dates_title': 'KEY DATES',
  'dates': [
    ('Jul 7', 'Athlete registration opens (10 AM, Brasília time)'),
    ('Sep 30', 'Deadline for athlete registration and document approval'),
    ('Oct 31 - Nov 2', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'ATHLETE CHECKLIST',
  'checklist': [
    'I got my team invite and used the SAME e-mail to register',
    'I created my account and verified my e-mail (clicked the link)',
    'I logged in to the Athletes Area',
    'I uploaded a photo with my face visible',
    'I uploaded my official photo ID (national ID, driver license or passport)',
    'I am under 18: I uploaded the signed guardian authorization',
    'I will bring the same document on game day',
  ],
  'final_footer': 'Welcome to the Brasil Flag World Championship 2026. See you in Leme, SP!',
},
'es': {
  'filename': 'Guia-Ilustrada-Inscripcion-Atletas-BFWC2026-ES.pdf',
  'title': 'Guía Ilustrada de Inscripción de Atletas',
  'subtitle': 'Brasil Flag World Championship 2026 · Paso a paso con imágenes, desde la invitación del equipo hasta la inscripción confirmada',
  'footer': 'Guía Ilustrada de Inscripción de Atletas · BFWC 2026 · página {n}',
  'deadlines_title': 'CÓMO FUNCIONA LA INSCRIPCIÓN DEL ATLETA',
  'deadlines_body': 'Tu inscripción empieza por <b>tu equipo</b>: el club te agrega al roster y recibes un <b>correo de invitación</b>. Creas tu cuenta con el <b>mismo correo</b>, lo confirmas, entras al Área de Atletas y <b>completas el perfil</b> — foto, documento oficial con foto y, si eres <b>menor de 18</b>, la autorización del responsable.<br/>La inscripción de atletas abre el <b>07/07 a las 10h</b> (Brasília). Funciona en el celular y en la computadora.<br/>¿Dudas? Correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'howto': '<b>Cómo usar esta guía:</b> las flechas amarillas en las imágenes muestran exactamente dónde hacer clic en cada paso. (Pantallas en portugués; el diseño es idéntico en español.)',
  'timeline_title': 'RESUMEN — TU RECORRIDO COMO ATLETA',
  'timeline': [
    ('1', 'Invitación del equipo', 'Tu club te agrega al roster y recibes un correo'),
    ('2', 'Crear tu cuenta', 'Con el <b>mismo correo</b> de la invitación (desde 07/07, 10h)'),
    ('3', 'Confirmar el correo', 'Haz clic en el enlace enviado para activar la cuenta'),
    ('4', 'Entrar al Área de Atletas', 'Inicia sesión con correo y contraseña'),
    ('5', 'Completar el perfil y subir documentos', 'Foto, documento con foto y (si es menor) autorización del responsable'),
    ('✓', '<b>¡Inscripción confirmada!</b>', 'Nos vemos en Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Recibir la invitación y crear la cuenta', 'steps': [
      {'h': '1. Tu equipo te invita',
       'b': 'La inscripción del atleta parte de <b>tu club</b>: el entrenador/responsable te agrega al roster de una categoría (Masculino, Femenino, Sub-15 o Sub-12). Recibes un <b>correo de invitación</b> del BFWC 2026. Guarda ese correo — usarás la misma dirección para inscribirte.'},
      {'h': '2. Abre la inscripción y elige el idioma',
       'b': 'Entra a <b>/portal/atletas/cadastro</b>. En la primera pantalla, selecciona el idioma.',
       'img': 'img/pt-atletas/01-idioma.png', 'cap': 'Haz clic en tu idioma para continuar (aquí: Português).'},
      {'h': '3. Paso 1 · Completa tus datos',
       'b': 'Usa el <b>mismo correo de la invitación</b> (el aviso amarillo lo recuerda). Completa nombre, correo, fecha de nacimiento, nacionalidad, WhatsApp, Instagram y posición, y haz clic en <b>Continuar</b>.',
       'img': 'img/pt-atletas/02-cadastro.png', 'cap': 'Usa el mismo correo registrado por tu club.'},
      {'h': '4. Crea la contraseña, acepta los términos y confirma el correo',
       'b': 'En los pasos siguientes, define una contraseña (<b>mín. 8 caracteres</b>), acepta los términos y haz clic en <b>Crear cuenta</b>. Luego abre el <b>correo de confirmación</b> (revisa el spam) y haz clic en el enlace para <b>activar la cuenta</b>.'},
    ]},
    {'title': 'PARTE 2 — Entrar y completar el perfil', 'steps': [
      {'h': '5. Inicia sesión en el Área de Atletas',
       'b': 'Entra a <b>/portal/atletas/login</b>, elige el idioma e inicia sesión con <b>tu correo</b> (el mismo de la invitación) y tu contraseña.',
       'img': 'img/pt-atletas/03-login.png', 'cap': 'Área de Atletas — elige el idioma para entrar.'},
      {'h': '6. Sube tu foto y tu documento con foto',
       'b': 'En la pestaña <b>Perfil</b>, sube una <b>foto con el rostro visible</b> y adjunta un <b>documento oficial con foto</b> (DNI, licencia o pasaporte). <b>Es el mismo documento que deberás llevar el día de los juegos.</b>',
       'img': 'img/pt-atletas/04-foto-documento.png', 'cap': 'Haz clic para agregar la foto y para adjuntar el documento.'},
      {'h': '7. Acepta los términos y guarda',
       'b': 'Completa los datos personales, contacto de emergencia y datos deportivos, marca los <b>5 términos obligatorios</b> y haz clic en <b>Guardar progreso</b>. Con todo completo, tu <b>inscripción queda confirmada</b>.',
       'img': 'img/pt-atletas/05-termos.png', 'cap': 'Acepta los 5 términos y haz clic en "Guardar progreso".'},
      {'h': '8. ¿Menor de 18? Autorización del responsable',
       'b': 'Si eres <b>menor de 18</b> en la fecha del evento (Sub-15 y Sub-12), es obligatorio subir la <b>autorización del responsable</b>. <b>Descarga el modelo (PDF)</b>, pide al responsable legal que lo complete y firme, y <b>adjunta</b> el archivo. Plazo: <b>30/09</b>.',
       'img': 'img/pt-atletas/06-autorizacao.png', 'cap': 'Descarga el modelo, consigue la firma y adjunta la autorización.'},
    ]},
    {'title': 'PARTE 3 — El día del juego', 'steps': [
      {'h': '9. Lleva el mismo documento',
       'b': 'El día de los juegos, lleva el <b>mismo documento oficial con foto</b> que subiste — se usará para validar tu identidad en la acreditación. ¿Dudas? Habla con el responsable de tu equipo o con la organización (<b>contato@brasilflag.com</b>).'},
    ]},
  ],
  'dates_title': 'FECHAS IMPORTANTES',
  'dates': [
    ('07/07', 'Apertura de la inscripción de atletas (10h, hora de Brasília)'),
    ('30/09', 'Plazo final de inscripción de atletas y aprobación de documentos'),
    ('31/10 al 02/11', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'CHECKLIST DEL ATLETA',
  'checklist': [
    'Recibí la invitación de mi equipo y usé el MISMO correo al inscribirme',
    'Creé mi cuenta y confirmé el correo (hice clic en el enlace)',
    'Entré al Área de Atletas con correo y contraseña',
    'Subí una foto con el rostro visible',
    'Subí mi documento oficial con foto (DNI, licencia o pasaporte)',
    'Soy menor de 18: subí la autorización del responsable firmada',
    'Llevaré el mismo documento el día de los juegos',
  ],
  'final_footer': '¡Bienvenido al Brasil Flag World Championship 2026. Nos vemos en Leme, SP!',
},
}
