# -*- coding: utf-8 -*-
"""Conteúdo do guia de TEXTO dos ATLETAS (PT) — BFWC 2026.
Mesmo esquema do content_txt.py: h=título, b=corpo (<b>), table opcional, after opcional."""

TXT = {
'pt': {
  'filename': 'Guia-de-Inscricao-dos-Atletas-BFWC2026-PT.pdf',
  'title': 'Guia de Inscrição dos Atletas',
  'subtitle': 'Brasil Flag World Championship 2026 · Passo a passo, do convite do seu time até a inscrição confirmada',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'COMO FUNCIONA A INSCRIÇÃO DO ATLETA',
  'deadlines_body': 'A sua inscrição começa pelo <b>seu time</b>: o clube adiciona você ao roster de uma categoria e você recebe um <b>e-mail de convite</b>. Você cria sua conta usando <b>exatamente esse mesmo e-mail</b>, confirma o e-mail, entra na Área dos Atletas e <b>completa o perfil</b> — foto, documento oficial com foto e, se você for <b>menor de 18 anos</b>, a autorização do responsável. A inscrição dos atletas abre em <b>07/07 às 10h</b> (horário de Brasília). Funciona no celular e no computador.',
  'contact': 'Dúvidas? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'RESUMO — SUA JORNADA COMO ATLETA',
  'timeline': [
    ('1', 'Convite do time', 'Seu clube adiciona você ao roster e você recebe um e-mail'),
    ('2', 'Criar sua conta', 'Com o <b>mesmo e-mail</b> do convite (a partir de 07/07, 10h)'),
    ('3', 'Confirmar o e-mail', 'Clique no link enviado para ativar a conta'),
    ('4', 'Entrar na Área dos Atletas', 'Login com e-mail e senha'),
    ('5', 'Completar o perfil e enviar documentos', 'Foto, documento com foto e (se menor) autorização do responsável'),
    ('✓', '<b>Inscrição confirmada!</b>', 'Nos vemos em Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Receber o convite e criar a conta', 'steps': [
      {'h': 'Seu time convida você',
       'b': 'A inscrição do atleta é feita a partir do <b>seu clube</b>: o técnico ou responsável adiciona você ao roster de uma categoria (Masculino, Feminino, Sub-15 ou Sub-12). Assim que isso acontece, você recebe um <b>e-mail de convite</b> do BFWC 2026. <b>Guarde o e-mail em que recebeu o convite</b> — você vai usar o mesmo endereço no cadastro.'},
      {'h': 'Abra a página de cadastro do atleta',
       'b': 'No convite há um botão para o cadastro, ou acesse direto <b>www.brasilflagworldchampionship.com/portal/atletas/cadastro</b>. A inscrição dos atletas abre em <b>07/07 às 10h</b> (Brasília). Funciona no celular e no computador.'},
      {'h': 'Escolha o idioma',
       'b': 'Na primeira tela, selecione <b>Português</b>, <b>English</b> ou <b>Español</b>. Todo o portal seguirá o idioma escolhido.'},
      {'h': 'Etapa 1 · Preencha seus dados',
       'b': 'Use o <b>mesmo e-mail do convite</b>. Campos com * são obrigatórios:',
       'table': [
         ('Nome completo *', 'Seu nome como no documento oficial'),
         ('E-mail *', 'O MESMO e-mail em que você recebeu o convite'),
         ('Data de nascimento *', 'Define sua categoria e se você é menor de idade'),
         ('Nacionalidade', 'Seu país'),
         ('WhatsApp', 'Com DDI/DDD, ex.: +55 11 99999-0000'),
         ('Instagram', '@ do seu perfil (opcional)'),
         ('Posição', 'Sua posição em campo (opcional)'),
         ('Foto', 'Foto sua com o rosto visível (usada no credenciamento)'),
         ('Histórico esportivo', 'Times, títulos e tempo de prática (opcional)'),
       ],
       'after': 'Preencheu tudo? Clique em <b>Continuar</b>.'},
      {'h': 'Etapa 2 · Crie a senha e aceite os termos',
       'b': 'Defina uma senha com <b>no mínimo 8 caracteres</b> e confirme. Leia e marque os termos de <b>uso de imagem</b>, <b>Regulamento Oficial</b>, <b>saúde e riscos</b> e <b>privacidade (LGPD)</b>. Depois clique em <b>Criar conta</b>.'},
      {'h': 'Confirme o seu e-mail',
       'b': 'Você receberá um e-mail de confirmação. Abra-o (verifique também a caixa de <b>spam</b>) e clique no link para <b>ativar a conta</b>. Sem essa confirmação, o login não é liberado.'},
    ]},
    {'title': 'PARTE 2 — Entrar e completar o perfil', 'steps': [
      {'h': 'Faça login na Área dos Atletas',
       'b': 'Acesse <b>/portal/atletas/login</b> e entre com o <b>seu e-mail</b> (o mesmo do convite) e a senha que você criou.'},
      {'h': 'Se aparecer uma mensagem de erro, veja o que significa',
       'b': '<b>“E-mail não verificado”</b>: abra o e-mail de confirmação e clique no link (verifique o spam). · <b>“Senha incorreta”</b>: confira a senha. · <b>“Nenhuma conta encontrada”</b>: confira o e-mail — precisa ser exatamente o mesmo do convite. · <b>Esqueceu a senha?</b> Clique em “Esqueci a senha”, informe o e-mail e siga o link enviado (vale por 1 hora) para criar uma nova.'},
      {'h': 'Aba Perfil · Confira seus dados e a foto',
       'b': 'O portal abre na aba <b>Perfil</b>. Confira seus dados e envie uma <b>foto com o rosto visível</b> (nada de foto escura ou de longe) — ela é usada no seu credenciamento.'},
      {'h': 'Envie seu documento oficial com foto',
       'b': 'Anexe um <b>documento oficial com foto</b> — RG, CNH ou passaporte (imagem ou PDF). <b>É o mesmo documento que você deverá levar no dia dos jogos</b> para validar sua identidade, então use um documento válido e legível.'},
      {'h': 'Menor de 18 anos? Envie a autorização do responsável',
       'b': 'Se na data do evento você tiver <b>menos de 18 anos</b> (categorias <b>Sub-15</b> e <b>Sub-12</b>), é obrigatório enviar a <b>autorização do responsável</b>. No portal, <b>baixe o modelo</b> (Anexo II), peça para o pai, mãe ou responsável legal <b>preencher e assinar</b>, e anexe o arquivo. Sem isso, a inscrição não é concluída.'},
      {'h': 'Pronto · Inscrição confirmada',
       'b': 'Com o perfil completo (dados, foto e documento — e a autorização, se menor), sua <b>inscrição fica confirmada</b>. A organização faz a <b>aprovação dos documentos até 30/09</b>. Você pode voltar ao portal quando quiser para conferir ou atualizar seus dados.'},
    ]},
    {'title': 'PARTE 3 — Dicas e no dia do jogo', 'steps': [
      {'h': 'Leve o mesmo documento no dia',
       'b': 'No dia dos jogos, leve o <b>mesmo documento oficial com foto</b> que você anexou no portal — ele será usado para validar sua identidade no credenciamento.'},
      {'h': 'Mantenha seus dados atualizados',
       'b': 'Mudou o WhatsApp, a foto ou precisa trocar o documento? Entre na Área dos Atletas e atualize — é rápido e ajuda a organização a falar com você.'},
      {'h': 'Ficou com dúvida?',
       'b': 'Fale com o responsável do seu time ou com a organização: <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>.'},
    ]},
  ],
  'dates_title': 'DATAS IMPORTANTES',
  'dates': [
    ('07/07', 'Abertura da inscrição dos atletas (10h, horário de Brasília)'),
    ('30/09', 'Prazo final da inscrição de atletas e da aprovação de documentos'),
    ('31/10 a 02/11', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'CHECKLIST DO ATLETA',
  'checklist': [
    'Recebi o convite do meu time e usei o MESMO e-mail no cadastro',
    'Criei minha conta e confirmei o e-mail (cheguei a clicar no link)',
    'Entrei na Área dos Atletas com e-mail e senha',
    'Completei o perfil e enviei uma foto com o rosto visível',
    'Enviei meu documento oficial com foto (RG, CNH ou passaporte)',
    'Sou menor de 18: enviei a autorização do responsável assinada',
    'Vou levar o mesmo documento no dia dos jogos',
  ],
},
}
