# -*- coding: utf-8 -*-
"""Conteúdo do guia de TEXTO dos ATLETAS (PT) — BFWC 2026.
Mesmo esquema do content_txt.py: h=título, b=corpo (<b>), table opcional, after opcional."""

TXT = {
'pt': {
  'filename': 'Guia-de-Inscricao-dos-Atletas-BFWC2026-PT.pdf',
  'title': 'Guia de Inscrição dos Atletas',
  'subtitle': 'Brasil Flag World Championship 2026 · Passo a passo, do convite do seu time até a inscrição confirmada',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'COMO FUNCIONA A INSCRIÇÃO DO ATLETA',
  'deadlines_body': 'A sua inscrição começa pelo <b>seu time</b>: o clube adiciona você ao roster de uma categoria e você recebe um <b>e-mail de convite</b>. Você cria sua conta usando <b>exatamente esse mesmo e-mail</b>, confirma o e-mail, entra na Área dos Atletas e <b>completa o perfil</b> — foto, documento oficial com foto e, se você for <b>menor de 18 anos</b>, a autorização do responsável. A inscrição dos atletas abre em <b>07/07 às 10h</b> (horário de Brasília). Funciona no celular e no computador.',
  'contact': 'Dúvidas? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'RESUMO — SUA JORNADA COMO ATLETA',
  'timeline': [
    ('1', 'Convite do time', 'Seu clube adiciona você ao roster e você recebe um e-mail'),
    ('2', 'Criar sua conta', 'Com o <b>mesmo e-mail</b> do convite (a partir de 07/07, 10h)'),
    ('3', 'Confirmar o e-mail', 'Clique no link enviado para ativar a conta'),
    ('4', 'Entrar na Área dos Atletas', 'Login com e-mail e senha'),
    ('5', 'Completar o perfil e enviar documentos', 'Foto, documento com foto e (se menor) autorização do responsável'),
    ('✓', '<b>Inscrição confirmada!</b>', 'Nos vemos em Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Receber o convite e criar a conta', 'steps': [
      {'h': 'Seu time convida você',
       'b': 'A inscrição do atleta é feita a partir do <b>seu clube</b>: o técnico ou responsável adiciona você ao roster de uma categoria (Masculino, Feminino, Sub-15 ou Sub-12). Assim que isso acontece, você recebe um <b>e-mail de convite</b> do BFWC 2026. <b>Guarde o e-mail em que recebeu o convite</b> — você vai usar o mesmo endereço no cadastro.'},
      {'h': 'Abra a página de cadastro do atleta',
       'b': 'No convite há um botão para o cadastro, ou acesse direto <b>www.brasilflagworldchampionship.com/portal/atletas/cadastro</b>. A inscrição dos atletas abre em <b>07/07 às 10h</b> (Brasília). Funciona no celular e no computador.'},
      {'h': 'Escolha o idioma',
       'b': 'Na primeira tela, selecione <b>Português</b>, <b>English</b> ou <b>Español</b>. Todo o portal seguirá o idioma escolhido.'},
      {'h': 'Etapa 1 · Preencha seus dados',
       'b': 'Use o <b>mesmo e-mail do convite</b>. Campos com * são obrigatórios:',
       'table': [
         ('Nome completo *', 'Seu nome como no documento oficial'),
         ('E-mail *', 'O MESMO e-mail em que você recebeu o convite'),
         ('Data de nascimento *', 'Define sua categoria e se você é menor de idade'),
         ('Nacionalidade', 'Seu país'),
         ('WhatsApp', 'Com DDI/DDD, ex.: +55 11 99999-0000'),
         ('Instagram', '@ do seu perfil (opcional)'),
         ('Posição', 'Sua posição em campo (opcional)'),
         ('Foto', 'Foto sua com o rosto visível (usada no credenciamento)'),
         ('Histórico esportivo', 'Times, títulos e tempo de prática (opcional)'),
       ],
       'after': 'Preencheu tudo? Clique em <b>Continuar</b>.'},
      {'h': 'Etapa 2 · Crie a senha e aceite os termos',
       'b': 'Defina uma senha com <b>no mínimo 8 caracteres</b> e confirme. Leia e marque os termos de <b>uso de imagem</b>, <b>Regulamento Oficial</b>, <b>saúde e riscos</b> e <b>privacidade (LGPD)</b>. Depois clique em <b>Criar conta</b>.'},
      {'h': 'Confirme o seu e-mail',
       'b': 'Você receberá um e-mail de confirmação. Abra-o (verifique também a caixa de <b>spam</b>) e clique no link para <b>ativar a conta</b>. Sem essa confirmação, o login não é liberado.'},
    ]},
    {'title': 'PARTE 2 — Entrar e completar o perfil', 'steps': [
      {'h': 'Faça login na Área dos Atletas',
       'b': 'Acesse <b>/portal/atletas/login</b> e entre com o <b>seu e-mail</b> (o mesmo do convite) e a senha que você criou.'},
      {'h': 'Se aparecer uma mensagem de erro, veja o que significa',
       'b': '<b>“E-mail não verificado”</b>: abra o e-mail de confirmação e clique no link (verifique o spam). · <b>“Senha incorreta”</b>: confira a senha. · <b>“Nenhuma conta encontrada”</b>: confira o e-mail — precisa ser exatamente o mesmo do convite. · <b>Esqueceu a senha?</b> Clique em “Esqueci a senha”, informe o e-mail e siga o link enviado (vale por 1 hora) para criar uma nova.'},
      {'h': 'Aba Perfil · Confira seus dados e a foto',
       'b': 'O portal abre na aba <b>Perfil</b>. Confira seus dados e envie uma <b>foto com o rosto visível</b> (nada de foto escura ou de longe) — ela é usada no seu credenciamento.'},
      {'h': 'Envie seu documento oficial com foto',
       'b': 'Anexe um <b>documento oficial com foto</b> — RG, CNH ou passaporte (imagem ou PDF). <b>É o mesmo documento que você deverá levar no dia dos jogos</b> para validar sua identidade, então use um documento válido e legível.'},
      {'h': 'Menor de 18 anos? Envie a autorização do responsável',
       'b': 'Se na data do evento você tiver <b>menos de 18 anos</b> (categorias <b>Sub-15</b> e <b>Sub-12</b>), é obrigatório enviar a <b>autorização do responsável</b>. No portal, <b>baixe o modelo</b> (Anexo II), peça para o pai, mãe ou responsável legal <b>preencher e assinar</b>, e anexe o arquivo. Sem isso, a inscrição não é concluída.'},
      {'h': 'Pronto · Inscrição confirmada',
       'b': 'Com o perfil completo (dados, foto e documento — e a autorização, se menor), sua <b>inscrição fica confirmada</b>. A organização faz a <b>aprovação dos documentos até 30/09</b>. Você pode voltar ao portal quando quiser para conferir ou atualizar seus dados.'},
    ]},
    {'title': 'PARTE 3 — Dicas e no dia do jogo', 'steps': [
      {'h': 'Leve o mesmo documento no dia',
       'b': 'No dia dos jogos, leve o <b>mesmo documento oficial com foto</b> que você anexou no portal — ele será usado para validar sua identidade no credenciamento.'},
      {'h': 'Mantenha seus dados atualizados',
       'b': 'Mudou o WhatsApp, a foto ou precisa trocar o documento? Entre na Área dos Atletas e atualize — é rápido e ajuda a organização a falar com você.'},
      {'h': 'Ficou com dúvida?',
       'b': 'Fale com o responsável do seu time ou com a organização: <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>.'},
    ]},
  ],
  'dates_title': 'DATAS IMPORTANTES',
  'dates': [
    ('07/07', 'Abertura da inscrição dos atletas (10h, horário de Brasília)'),
    ('30/09', 'Prazo final da inscrição de atletas e da aprovação de documentos'),
    ('31/10 a 02/11', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'CHECKLIST DO ATLETA',
  'checklist': [
    'Recebi o convite do meu time e usei o MESMO e-mail no cadastro',
    'Criei minha conta e confirmei o e-mail (cheguei a clicar no link)',
    'Entrei na Área dos Atletas com e-mail e senha',
    'Completei o perfil e enviei uma foto com o rosto visível',
    'Enviei meu documento oficial com foto (RG, CNH ou passaporte)',
    'Sou menor de 18: enviei a autorização do responsável assinada',
    'Vou levar o mesmo documento no dia dos jogos',
  ],
},

'en': {
  'filename': 'Athlete-Registration-Guide-BFWC2026-EN.pdf',
  'title': 'Athlete Registration Guide',
  'subtitle': 'Brasil Flag World Championship 2026 · Step by step, from your team invite to a confirmed registration',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'HOW ATHLETE REGISTRATION WORKS',
  'deadlines_body': 'Your registration starts with <b>your team</b>: the club adds you to the roster and you receive an <b>invitation e-mail</b>. You create your account using <b>the exact same e-mail</b>, verify it, log in to the Athletes Area and <b>complete your profile</b> — photo, official photo ID and, if you are <b>under 18</b>, the guardian authorization. Athlete registration opens on <b>July 7 at 10 AM</b> (Brasília time). Works on phone and computer.',
  'contact': 'Questions? E-mail <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'SUMMARY — YOUR JOURNEY AS AN ATHLETE',
  'timeline': [
    ('1', 'Team invite', 'Your club adds you to the roster and you get an e-mail'),
    ('2', 'Create your account', 'With the <b>same e-mail</b> from the invite (from July 7, 10 AM)'),
    ('3', 'Verify your e-mail', 'Click the link sent to activate the account'),
    ('4', 'Log in to the Athletes Area', 'Log in with e-mail and password'),
    ('5', 'Complete your profile and upload documents', 'Photo, photo ID and (if a minor) guardian authorization'),
    ('✓', '<b>Registration confirmed!</b>', 'See you in Leme, SP — Oct 31'),
  ],
  'parts': [
    {'title': 'PART 1 — Get the invite and create your account', 'steps': [
      {'h': 'Your team invites you',
       'b': 'Athlete registration starts from <b>your club</b>: the coach/manager adds you to a category roster (Men, Women, U-15 or U-12). You receive an <b>invitation e-mail</b> from BFWC 2026. Keep that e-mail — you will use the same address to register.'},
      {'h': 'Open the athlete registration page',
       'b': 'Go to <b>www.brasilflagworldchampionship.com/portal/atletas/cadastro</b>. Athlete registration opens on <b>July 7 at 10 AM</b> (Brasília). Works on phone and computer.'},
      {'h': 'Choose the language',
       'b': 'On the first screen, select <b>Português</b>, <b>English</b> or <b>Español</b>. The whole portal follows your choice.'},
      {'h': 'Step 1 · Fill in your details',
       'b': 'Use the <b>same e-mail from the invite</b>. Fields marked * are required:',
       'table': [
         ('Full name *', 'Your name as on your official ID'),
         ('E-mail *', 'The SAME e-mail where you received the invite'),
         ('Date of birth *', 'Sets your category and whether you are a minor'),
         ('Nationality', 'Your country'),
         ('WhatsApp', 'With country/area code, e.g. +55 11 99999-0000'),
         ('Instagram', 'Your @ handle (optional)'),
         ('Position', 'Your position on the field (optional)'),
         ('Photo', 'A clear photo of your face (used for accreditation)'),
         ('Sports history', 'Teams, titles and time playing (optional)'),
       ],
       'after': 'All set? Click <b>Continue</b>.'},
      {'h': 'Step 2 · Create a password and accept the terms',
       'b': 'Set a password with <b>at least 8 characters</b> and confirm it. Read and check the terms for <b>image use</b>, <b>Official Rules</b>, <b>health & risks</b> and <b>privacy (LGPD)</b>. Then click <b>Create account</b>.'},
      {'h': 'Verify your e-mail',
       'b': 'You will get a confirmation e-mail. Open it (check <b>spam</b> too) and click the link to <b>activate the account</b>. Without this, login is not enabled.'},
    ]},
    {'title': 'PART 2 — Log in and complete your profile', 'steps': [
      {'h': 'Log in to the Athletes Area',
       'b': 'Go to <b>/portal/atletas/login</b> and sign in with <b>your e-mail</b> (the same from the invite) and your password.'},
      {'h': 'If you see an error message, here is what it means',
       'b': '<b>"E-mail not verified"</b>: open the confirmation e-mail and click the link (check spam). · <b>"Wrong password"</b>: check your password. · <b>"No account found"</b>: check the e-mail — it must be exactly the one from the invite. · <b>Forgot your password?</b> Click "Forgot password", enter your e-mail and follow the link (valid for 1 hour).'},
      {'h': 'Profile tab · Check your details and photo',
       'b': 'The portal opens on the <b>Profile</b> tab. Check your details and upload a <b>photo with your face clearly visible</b> — it is used for your accreditation.'},
      {'h': 'Upload your official photo ID',
       'b': 'Attach an <b>official photo ID</b> — national ID, driver license or passport (image or PDF). <b>It is the same document you must bring on game day</b> to verify your identity, so use a valid, legible one.'},
      {'h': 'Under 18? Upload the guardian authorization',
       'b': 'If you are <b>under 18</b> on the event date (U-15 and U-12), you must upload the <b>guardian authorization</b>. In the portal, <b>download the template</b> (Annex II), have your parent or legal guardian fill it in and sign it, and attach the file. Without it, registration is not completed.'},
      {'h': 'Done · Registration confirmed',
       'b': 'With your profile complete (details, photo and document — plus the authorization if a minor), your <b>registration is confirmed</b>. The organization approves documents <b>by Sep 30</b>. You can return to the portal anytime to review or update your data.'},
    ]},
    {'title': 'PART 3 — Tips and game day', 'steps': [
      {'h': 'Bring the same document on game day',
       'b': 'On game day, bring the <b>same official photo ID</b> you uploaded in the portal — it will be used to verify your identity at accreditation.'},
      {'h': 'Keep your data up to date',
       'b': 'Changed your WhatsApp or photo, or need to replace the document? Log in to the Athletes Area and update it.'},
      {'h': 'Questions?',
       'b': 'Talk to your team manager or the organization: <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>.'},
    ]},
  ],
  'dates_title': 'KEY DATES',
  'dates': [
    ('Jul 7', 'Athlete registration opens (10 AM, Brasília time)'),
    ('Sep 30', 'Deadline for athlete registration and document approval'),
    ('Oct 31 - Nov 2', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'ATHLETE CHECKLIST',
  'checklist': [
    'I got my team invite and used the SAME e-mail to register',
    'I created my account and verified my e-mail (clicked the link)',
    'I logged in to the Athletes Area',
    'I completed my profile and uploaded a photo with my face visible',
    'I uploaded my official photo ID (national ID, driver license or passport)',
    'I am under 18: I uploaded the signed guardian authorization',
    'I will bring the same document on game day',
  ],
},
'es': {
  'filename': 'Guia-de-Inscripcion-de-Atletas-BFWC2026-ES.pdf',
  'title': 'Guía de Inscripción de Atletas',
  'subtitle': 'Brasil Flag World Championship 2026 · Paso a paso, desde la invitación de tu equipo hasta la inscripción confirmada',
  'footer': 'Brasil Flag World Championship 2026 · Leme, SP · www.brasilflagworldchampionship.com · contato@brasilflag.com',
  'deadlines_title': 'CÓMO FUNCIONA LA INSCRIPCIÓN DEL ATLETA',
  'deadlines_body': 'Tu inscripción empieza por <b>tu equipo</b>: el club te agrega al roster y recibes un <b>correo de invitación</b>. Creas tu cuenta usando <b>exactamente el mismo correo</b>, lo confirmas, entras al Área de Atletas y <b>completas el perfil</b> — foto, documento oficial con foto y, si eres <b>menor de 18</b>, la autorización del responsable. La inscripción de atletas abre el <b>07/07 a las 10h</b> (hora de Brasília). Funciona en el celular y en la computadora.',
  'contact': '¿Dudas? Correo <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>',
  'timeline_title': 'RESUMEN — TU RECORRIDO COMO ATLETA',
  'timeline': [
    ('1', 'Invitación del equipo', 'Tu club te agrega al roster y recibes un correo'),
    ('2', 'Crear tu cuenta', 'Con el <b>mismo correo</b> de la invitación (desde 07/07, 10h)'),
    ('3', 'Confirmar el correo', 'Haz clic en el enlace enviado para activar la cuenta'),
    ('4', 'Entrar al Área de Atletas', 'Inicia sesión con correo y contraseña'),
    ('5', 'Completar el perfil y subir documentos', 'Foto, documento con foto y (si es menor) autorización del responsable'),
    ('✓', '<b>¡Inscripción confirmada!</b>', 'Nos vemos en Leme, SP — 31/10'),
  ],
  'parts': [
    {'title': 'PARTE 1 — Recibir la invitación y crear la cuenta', 'steps': [
      {'h': 'Tu equipo te invita',
       'b': 'La inscripción del atleta parte de <b>tu club</b>: el entrenador/responsable te agrega al roster de una categoría (Masculino, Femenino, Sub-15 o Sub-12). Recibes un <b>correo de invitación</b> del BFWC 2026. Guarda ese correo — usarás la misma dirección para inscribirte.'},
      {'h': 'Abre la página de inscripción del atleta',
       'b': 'Entra a <b>www.brasilflagworldchampionship.com/portal/atletas/cadastro</b>. La inscripción de atletas abre el <b>07/07 a las 10h</b> (Brasília). Funciona en el celular y en la computadora.'},
      {'h': 'Elige el idioma',
       'b': 'En la primera pantalla, selecciona <b>Português</b>, <b>English</b> o <b>Español</b>. Todo el portal seguirá tu elección.'},
      {'h': 'Paso 1 · Completa tus datos',
       'b': 'Usa el <b>mismo correo de la invitación</b>. Los campos con * son obligatorios:',
       'table': [
         ('Nombre completo *', 'Tu nombre como en tu documento oficial'),
         ('Correo *', 'El MISMO correo donde recibiste la invitación'),
         ('Fecha de nacimiento *', 'Define tu categoría y si eres menor de edad'),
         ('Nacionalidad', 'Tu país'),
         ('WhatsApp', 'Con código de país/área, ej.: +55 11 99999-0000'),
         ('Instagram', 'Tu @ (opcional)'),
         ('Posición', 'Tu posición en la cancha (opcional)'),
         ('Foto', 'Una foto nítida de tu rostro (usada en la acreditación)'),
         ('Historial deportivo', 'Equipos, títulos y tiempo jugando (opcional)'),
       ],
       'after': '¿Listo? Haz clic en <b>Continuar</b>.'},
      {'h': 'Paso 2 · Crea la contraseña y acepta los términos',
       'b': 'Define una contraseña de <b>al menos 8 caracteres</b> y confírmala. Lee y marca los términos de <b>uso de imagen</b>, <b>Reglamento Oficial</b>, <b>salud y riesgos</b> y <b>privacidad (LGPD)</b>. Luego haz clic en <b>Crear cuenta</b>.'},
      {'h': 'Confirma tu correo',
       'b': 'Recibirás un correo de confirmación. Ábrelo (revisa también el <b>spam</b>) y haz clic en el enlace para <b>activar la cuenta</b>. Sin esto, el inicio de sesión no se habilita.'},
    ]},
    {'title': 'PARTE 2 — Entrar y completar el perfil', 'steps': [
      {'h': 'Inicia sesión en el Área de Atletas',
       'b': 'Entra a <b>/portal/atletas/login</b> con <b>tu correo</b> (el mismo de la invitación) y tu contraseña.'},
      {'h': 'Si aparece un mensaje de error, esto significa',
       'b': '<b>"Correo no verificado"</b>: abre el correo de confirmación y haz clic en el enlace (revisa el spam). · <b>"Contraseña incorrecta"</b>: revisa tu contraseña. · <b>"Ninguna cuenta encontrada"</b>: revisa el correo — debe ser exactamente el de la invitación. · <b>¿Olvidaste la contraseña?</b> Haz clic en "Olvidé la contraseña", ingresa tu correo y sigue el enlace (válido por 1 hora).'},
      {'h': 'Pestaña Perfil · Revisa tus datos y la foto',
       'b': 'El portal abre en la pestaña <b>Perfil</b>. Revisa tus datos y sube una <b>foto con el rostro visible</b> — se usa para tu acreditación.'},
      {'h': 'Sube tu documento oficial con foto',
       'b': 'Adjunta un <b>documento oficial con foto</b> — DNI/identificación, licencia de conducir o pasaporte (imagen o PDF). <b>Es el mismo documento que deberás llevar el día de los juegos</b> para validar tu identidad, así que usa uno válido y legible.'},
      {'h': '¿Menor de 18? Sube la autorización del responsable',
       'b': 'Si en la fecha del evento eres <b>menor de 18</b> (Sub-15 y Sub-12), es obligatorio subir la <b>autorización del responsable</b>. En el portal, <b>descarga el modelo</b> (Anexo II), pide a tu padre, madre o responsable legal que lo complete y firme, y adjunta el archivo. Sin esto, la inscripción no se concluye.'},
      {'h': 'Listo · Inscripción confirmada',
       'b': 'Con el perfil completo (datos, foto y documento — y la autorización, si es menor), tu <b>inscripción queda confirmada</b>. La organización aprueba los documentos <b>hasta el 30/09</b>. Puedes volver al portal cuando quieras para revisar o actualizar tus datos.'},
    ]},
    {'title': 'PARTE 3 — Consejos y el día del juego', 'steps': [
      {'h': 'Lleva el mismo documento el día del juego',
       'b': 'El día de los juegos, lleva el <b>mismo documento oficial con foto</b> que subiste al portal — se usará para validar tu identidad en la acreditación.'},
      {'h': 'Mantén tus datos actualizados',
       'b': '¿Cambiaste el WhatsApp o la foto, o necesitas reemplazar el documento? Entra al Área de Atletas y actualízalo.'},
      {'h': '¿Dudas?',
       'b': 'Habla con el responsable de tu equipo o con la organización: <b>contato@brasilflag.com</b> · WhatsApp <b>+55 (16) 99775-4522</b>.'},
    ]},
  ],
  'dates_title': 'FECHAS IMPORTANTES',
  'dates': [
    ('07/07', 'Apertura de la inscripción de atletas (10h, hora de Brasília)'),
    ('30/09', 'Plazo final de inscripción de atletas y aprobación de documentos'),
    ('31/10 al 02/11', 'Brasil Flag World Championship 2026 — Leme, SP'),
  ],
  'checklist_title': 'CHECKLIST DEL ATLETA',
  'checklist': [
    'Recibí la invitación de mi equipo y usé el MISMO correo al inscribirme',
    'Creé mi cuenta y confirmé el correo (hice clic en el enlace)',
    'Entré al Área de Atletas con correo y contraseña',
    'Completé el perfil y subí una foto con el rostro visible',
    'Subí mi documento oficial con foto (DNI, licencia o pasaporte)',
    'Soy menor de 18: subí la autorización del responsable firmada',
    'Llevaré el mismo documento el día de los juegos',
  ],
},
}
